// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fastvit_ip_pwconv_worker_Pipeline_VITIS_LOOP_182_310 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        sext_ln182_2,
        row_ok_load_2,
        p_ZL9pw_in_buf_2_7,
        p_ZL9pw_in_buf_2_7_ap_vld,
        p_ZL9pw_in_buf_2_0,
        p_ZL9pw_in_buf_2_0_ap_vld,
        p_ZL9pw_in_buf_2_1,
        p_ZL9pw_in_buf_2_1_ap_vld,
        p_ZL9pw_in_buf_2_2,
        p_ZL9pw_in_buf_2_2_ap_vld,
        p_ZL9pw_in_buf_2_3,
        p_ZL9pw_in_buf_2_3_ap_vld,
        p_ZL9pw_in_buf_2_4,
        p_ZL9pw_in_buf_2_4_ap_vld,
        p_ZL9pw_in_buf_2_5,
        p_ZL9pw_in_buf_2_5_ap_vld,
        p_ZL9pw_in_buf_2_6,
        p_ZL9pw_in_buf_2_6_ap_vld,
        p_ZL9pw_in_buf_2_8,
        p_ZL9pw_in_buf_2_8_ap_vld,
        p_ZL9pw_in_buf_2_9,
        p_ZL9pw_in_buf_2_9_ap_vld,
        p_ZL9pw_in_buf_2_10,
        p_ZL9pw_in_buf_2_10_ap_vld,
        p_ZL9pw_in_buf_2_11,
        p_ZL9pw_in_buf_2_11_ap_vld,
        p_ZL9pw_in_buf_2_12,
        p_ZL9pw_in_buf_2_12_ap_vld,
        p_ZL9pw_in_buf_2_13,
        p_ZL9pw_in_buf_2_13_ap_vld,
        p_ZL9pw_in_buf_2_14,
        p_ZL9pw_in_buf_2_14_ap_vld,
        p_ZL9pw_in_buf_2_16,
        p_ZL9pw_in_buf_2_16_ap_vld,
        p_ZL9pw_in_buf_2_17,
        p_ZL9pw_in_buf_2_17_ap_vld,
        p_ZL9pw_in_buf_2_18,
        p_ZL9pw_in_buf_2_18_ap_vld,
        p_ZL9pw_in_buf_2_19,
        p_ZL9pw_in_buf_2_19_ap_vld,
        p_ZL9pw_in_buf_2_20,
        p_ZL9pw_in_buf_2_20_ap_vld,
        p_ZL9pw_in_buf_2_21,
        p_ZL9pw_in_buf_2_21_ap_vld,
        p_ZL9pw_in_buf_2_22,
        p_ZL9pw_in_buf_2_22_ap_vld,
        p_ZL9pw_in_buf_2_24,
        p_ZL9pw_in_buf_2_24_ap_vld,
        p_ZL9pw_in_buf_2_25,
        p_ZL9pw_in_buf_2_25_ap_vld,
        p_ZL9pw_in_buf_2_26,
        p_ZL9pw_in_buf_2_26_ap_vld,
        p_ZL9pw_in_buf_2_27,
        p_ZL9pw_in_buf_2_27_ap_vld,
        p_ZL9pw_in_buf_2_28,
        p_ZL9pw_in_buf_2_28_ap_vld,
        p_ZL9pw_in_buf_2_29,
        p_ZL9pw_in_buf_2_29_ap_vld,
        p_ZL9pw_in_buf_2_30,
        p_ZL9pw_in_buf_2_30_ap_vld,
        p_ZL9pw_in_buf_2_32,
        p_ZL9pw_in_buf_2_32_ap_vld,
        p_ZL9pw_in_buf_2_33,
        p_ZL9pw_in_buf_2_33_ap_vld,
        p_ZL9pw_in_buf_2_34,
        p_ZL9pw_in_buf_2_34_ap_vld,
        p_ZL9pw_in_buf_2_35,
        p_ZL9pw_in_buf_2_35_ap_vld,
        p_ZL9pw_in_buf_2_36,
        p_ZL9pw_in_buf_2_36_ap_vld,
        p_ZL9pw_in_buf_2_37,
        p_ZL9pw_in_buf_2_37_ap_vld,
        p_ZL9pw_in_buf_2_38,
        p_ZL9pw_in_buf_2_38_ap_vld,
        p_ZL9pw_in_buf_2_40,
        p_ZL9pw_in_buf_2_40_ap_vld,
        p_ZL9pw_in_buf_2_41,
        p_ZL9pw_in_buf_2_41_ap_vld,
        p_ZL9pw_in_buf_2_42,
        p_ZL9pw_in_buf_2_42_ap_vld,
        p_ZL9pw_in_buf_2_43,
        p_ZL9pw_in_buf_2_43_ap_vld,
        p_ZL9pw_in_buf_2_44,
        p_ZL9pw_in_buf_2_44_ap_vld,
        p_ZL9pw_in_buf_2_45,
        p_ZL9pw_in_buf_2_45_ap_vld,
        p_ZL9pw_in_buf_2_46,
        p_ZL9pw_in_buf_2_46_ap_vld,
        p_ZL9pw_in_buf_2_48,
        p_ZL9pw_in_buf_2_48_ap_vld,
        p_ZL9pw_in_buf_2_49,
        p_ZL9pw_in_buf_2_49_ap_vld,
        p_ZL9pw_in_buf_2_50,
        p_ZL9pw_in_buf_2_50_ap_vld,
        p_ZL9pw_in_buf_2_51,
        p_ZL9pw_in_buf_2_51_ap_vld,
        p_ZL9pw_in_buf_2_52,
        p_ZL9pw_in_buf_2_52_ap_vld,
        p_ZL9pw_in_buf_2_53,
        p_ZL9pw_in_buf_2_53_ap_vld,
        p_ZL9pw_in_buf_2_54,
        p_ZL9pw_in_buf_2_54_ap_vld,
        p_ZL9pw_in_buf_2_56,
        p_ZL9pw_in_buf_2_56_ap_vld,
        p_ZL9pw_in_buf_2_57,
        p_ZL9pw_in_buf_2_57_ap_vld,
        p_ZL9pw_in_buf_2_58,
        p_ZL9pw_in_buf_2_58_ap_vld,
        p_ZL9pw_in_buf_2_59,
        p_ZL9pw_in_buf_2_59_ap_vld,
        p_ZL9pw_in_buf_2_60,
        p_ZL9pw_in_buf_2_60_ap_vld,
        p_ZL9pw_in_buf_2_61,
        p_ZL9pw_in_buf_2_61_ap_vld,
        p_ZL9pw_in_buf_2_62,
        p_ZL9pw_in_buf_2_62_ap_vld,
        p_ZL9pw_in_buf_2_15,
        p_ZL9pw_in_buf_2_15_ap_vld,
        p_ZL9pw_in_buf_2_23,
        p_ZL9pw_in_buf_2_23_ap_vld,
        p_ZL9pw_in_buf_2_31,
        p_ZL9pw_in_buf_2_31_ap_vld,
        p_ZL9pw_in_buf_2_39,
        p_ZL9pw_in_buf_2_39_ap_vld,
        p_ZL9pw_in_buf_2_47,
        p_ZL9pw_in_buf_2_47_ap_vld,
        p_ZL9pw_in_buf_2_55,
        p_ZL9pw_in_buf_2_55_ap_vld,
        p_ZL9pw_in_buf_2_63,
        p_ZL9pw_in_buf_2_63_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [31:0] m_axi_gmem0_0_WDATA;
output  [3:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [31:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [61:0] sext_ln182_2;
input  [0:0] row_ok_load_2;
output  [3:0] p_ZL9pw_in_buf_2_7;
output   p_ZL9pw_in_buf_2_7_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_0;
output   p_ZL9pw_in_buf_2_0_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_1;
output   p_ZL9pw_in_buf_2_1_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_2;
output   p_ZL9pw_in_buf_2_2_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_3;
output   p_ZL9pw_in_buf_2_3_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_4;
output   p_ZL9pw_in_buf_2_4_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_5;
output   p_ZL9pw_in_buf_2_5_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_6;
output   p_ZL9pw_in_buf_2_6_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_8;
output   p_ZL9pw_in_buf_2_8_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_9;
output   p_ZL9pw_in_buf_2_9_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_10;
output   p_ZL9pw_in_buf_2_10_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_11;
output   p_ZL9pw_in_buf_2_11_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_12;
output   p_ZL9pw_in_buf_2_12_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_13;
output   p_ZL9pw_in_buf_2_13_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_14;
output   p_ZL9pw_in_buf_2_14_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_16;
output   p_ZL9pw_in_buf_2_16_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_17;
output   p_ZL9pw_in_buf_2_17_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_18;
output   p_ZL9pw_in_buf_2_18_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_19;
output   p_ZL9pw_in_buf_2_19_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_20;
output   p_ZL9pw_in_buf_2_20_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_21;
output   p_ZL9pw_in_buf_2_21_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_22;
output   p_ZL9pw_in_buf_2_22_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_24;
output   p_ZL9pw_in_buf_2_24_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_25;
output   p_ZL9pw_in_buf_2_25_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_26;
output   p_ZL9pw_in_buf_2_26_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_27;
output   p_ZL9pw_in_buf_2_27_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_28;
output   p_ZL9pw_in_buf_2_28_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_29;
output   p_ZL9pw_in_buf_2_29_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_30;
output   p_ZL9pw_in_buf_2_30_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_32;
output   p_ZL9pw_in_buf_2_32_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_33;
output   p_ZL9pw_in_buf_2_33_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_34;
output   p_ZL9pw_in_buf_2_34_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_35;
output   p_ZL9pw_in_buf_2_35_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_36;
output   p_ZL9pw_in_buf_2_36_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_37;
output   p_ZL9pw_in_buf_2_37_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_38;
output   p_ZL9pw_in_buf_2_38_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_40;
output   p_ZL9pw_in_buf_2_40_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_41;
output   p_ZL9pw_in_buf_2_41_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_42;
output   p_ZL9pw_in_buf_2_42_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_43;
output   p_ZL9pw_in_buf_2_43_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_44;
output   p_ZL9pw_in_buf_2_44_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_45;
output   p_ZL9pw_in_buf_2_45_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_46;
output   p_ZL9pw_in_buf_2_46_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_48;
output   p_ZL9pw_in_buf_2_48_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_49;
output   p_ZL9pw_in_buf_2_49_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_50;
output   p_ZL9pw_in_buf_2_50_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_51;
output   p_ZL9pw_in_buf_2_51_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_52;
output   p_ZL9pw_in_buf_2_52_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_53;
output   p_ZL9pw_in_buf_2_53_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_54;
output   p_ZL9pw_in_buf_2_54_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_56;
output   p_ZL9pw_in_buf_2_56_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_57;
output   p_ZL9pw_in_buf_2_57_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_58;
output   p_ZL9pw_in_buf_2_58_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_59;
output   p_ZL9pw_in_buf_2_59_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_60;
output   p_ZL9pw_in_buf_2_60_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_61;
output   p_ZL9pw_in_buf_2_61_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_62;
output   p_ZL9pw_in_buf_2_62_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_15;
output   p_ZL9pw_in_buf_2_15_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_23;
output   p_ZL9pw_in_buf_2_23_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_31;
output   p_ZL9pw_in_buf_2_31_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_39;
output   p_ZL9pw_in_buf_2_39_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_47;
output   p_ZL9pw_in_buf_2_47_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_55;
output   p_ZL9pw_in_buf_2_55_ap_vld;
output  [3:0] p_ZL9pw_in_buf_2_63;
output   p_ZL9pw_in_buf_2_63_ap_vld;

reg ap_idle;
reg m_axi_gmem0_0_RREADY;
reg p_ZL9pw_in_buf_2_7_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_0;
reg p_ZL9pw_in_buf_2_0_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_1;
reg p_ZL9pw_in_buf_2_1_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_2;
reg p_ZL9pw_in_buf_2_2_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_3;
reg p_ZL9pw_in_buf_2_3_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_4;
reg p_ZL9pw_in_buf_2_4_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_5;
reg p_ZL9pw_in_buf_2_5_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_6;
reg p_ZL9pw_in_buf_2_6_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_8;
reg p_ZL9pw_in_buf_2_8_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_9;
reg p_ZL9pw_in_buf_2_9_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_10;
reg p_ZL9pw_in_buf_2_10_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_11;
reg p_ZL9pw_in_buf_2_11_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_12;
reg p_ZL9pw_in_buf_2_12_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_13;
reg p_ZL9pw_in_buf_2_13_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_14;
reg p_ZL9pw_in_buf_2_14_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_16;
reg p_ZL9pw_in_buf_2_16_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_17;
reg p_ZL9pw_in_buf_2_17_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_18;
reg p_ZL9pw_in_buf_2_18_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_19;
reg p_ZL9pw_in_buf_2_19_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_20;
reg p_ZL9pw_in_buf_2_20_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_21;
reg p_ZL9pw_in_buf_2_21_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_22;
reg p_ZL9pw_in_buf_2_22_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_24;
reg p_ZL9pw_in_buf_2_24_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_25;
reg p_ZL9pw_in_buf_2_25_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_26;
reg p_ZL9pw_in_buf_2_26_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_27;
reg p_ZL9pw_in_buf_2_27_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_28;
reg p_ZL9pw_in_buf_2_28_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_29;
reg p_ZL9pw_in_buf_2_29_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_30;
reg p_ZL9pw_in_buf_2_30_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_32;
reg p_ZL9pw_in_buf_2_32_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_33;
reg p_ZL9pw_in_buf_2_33_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_34;
reg p_ZL9pw_in_buf_2_34_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_35;
reg p_ZL9pw_in_buf_2_35_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_36;
reg p_ZL9pw_in_buf_2_36_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_37;
reg p_ZL9pw_in_buf_2_37_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_38;
reg p_ZL9pw_in_buf_2_38_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_40;
reg p_ZL9pw_in_buf_2_40_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_41;
reg p_ZL9pw_in_buf_2_41_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_42;
reg p_ZL9pw_in_buf_2_42_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_43;
reg p_ZL9pw_in_buf_2_43_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_44;
reg p_ZL9pw_in_buf_2_44_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_45;
reg p_ZL9pw_in_buf_2_45_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_46;
reg p_ZL9pw_in_buf_2_46_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_48;
reg p_ZL9pw_in_buf_2_48_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_49;
reg p_ZL9pw_in_buf_2_49_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_50;
reg p_ZL9pw_in_buf_2_50_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_51;
reg p_ZL9pw_in_buf_2_51_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_52;
reg p_ZL9pw_in_buf_2_52_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_53;
reg p_ZL9pw_in_buf_2_53_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_54;
reg p_ZL9pw_in_buf_2_54_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_56;
reg p_ZL9pw_in_buf_2_56_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_57;
reg p_ZL9pw_in_buf_2_57_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_58;
reg p_ZL9pw_in_buf_2_58_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_59;
reg p_ZL9pw_in_buf_2_59_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_60;
reg p_ZL9pw_in_buf_2_60_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_61;
reg p_ZL9pw_in_buf_2_61_ap_vld;
reg[3:0] p_ZL9pw_in_buf_2_62;
reg p_ZL9pw_in_buf_2_62_ap_vld;
reg p_ZL9pw_in_buf_2_15_ap_vld;
reg p_ZL9pw_in_buf_2_23_ap_vld;
reg p_ZL9pw_in_buf_2_31_ap_vld;
reg p_ZL9pw_in_buf_2_39_ap_vld;
reg p_ZL9pw_in_buf_2_47_ap_vld;
reg p_ZL9pw_in_buf_2_55_ap_vld;
reg p_ZL9pw_in_buf_2_63_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln182_reg_1019;
wire   [0:0] row_ok_load_2_read_reg_1010;
reg    ap_predicate_op101_read_state2;
reg    ap_block_state2_pp0_stage0_iter1_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln182_fu_252_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln182_reg_1019_pp0_iter1_reg;
wire   [2:0] trunc_ln182_fu_264_p1;
reg   [2:0] trunc_ln182_reg_1023;
reg   [2:0] trunc_ln182_reg_1023_pp0_iter1_reg;
wire   [3:0] trunc_ln186_fu_615_p1;
reg   [3:0] trunc_ln186_reg_1027;
reg   [3:0] tmp_15_reg_1039;
reg   [3:0] tmp_16_reg_1051;
reg   [3:0] tmp_17_reg_1063;
reg   [3:0] tmp_18_reg_1075;
reg   [3:0] tmp_19_reg_1087;
reg   [3:0] tmp_20_reg_1099;
reg   [3:0] tmp_s_reg_1111;
reg   [3:0] ap_phi_mux_storemerge427_phi_fu_233_p4;
wire   [3:0] ap_phi_reg_pp0_iter0_storemerge427_reg_229;
reg   [3:0] ap_phi_reg_pp0_iter1_storemerge427_reg_229;
reg   [3:0] ap_phi_reg_pp0_iter2_storemerge427_reg_229;
wire    ap_block_pp0_stage0_grp0;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [3:0] sw_3_fu_208;
wire   [3:0] add_ln182_fu_258_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_sw;
wire    ap_block_pp0_stage0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_299;
reg    ap_condition_550;
reg    ap_condition_554;
reg    ap_condition_557;
reg    ap_condition_561;
reg    ap_condition_564;
reg    ap_condition_568;
reg    ap_condition_571;
reg    ap_condition_575;
reg    ap_condition_578;
reg    ap_condition_582;
reg    ap_condition_585;
reg    ap_condition_589;
reg    ap_condition_592;
reg    ap_condition_596;
reg    ap_condition_599;
reg    ap_condition_603;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 sw_3_fu_208 = 4'd0;
#0 ap_done_reg = 1'b0;
end

fastvit_ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_299)) begin
        if (((row_ok_load_2_read_reg_1010 == 1'd0) & (icmp_ln182_reg_1019 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_storemerge427_reg_229 <= 4'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_storemerge427_reg_229 <= ap_phi_reg_pp0_iter1_storemerge427_reg_229;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln182_fu_252_p2 == 1'd0))) begin
            sw_3_fu_208 <= add_ln182_fu_258_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sw_3_fu_208 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln182_reg_1019 <= icmp_ln182_fu_252_p2;
        icmp_ln182_reg_1019_pp0_iter1_reg <= icmp_ln182_reg_1019;
        trunc_ln182_reg_1023 <= trunc_ln182_fu_264_p1;
        trunc_ln182_reg_1023_pp0_iter1_reg <= trunc_ln182_reg_1023;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_storemerge427_reg_229 <= ap_phi_reg_pp0_iter0_storemerge427_reg_229;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_15_reg_1039 <= {{m_axi_gmem0_0_RDATA[7:4]}};
        tmp_16_reg_1051 <= {{m_axi_gmem0_0_RDATA[11:8]}};
        tmp_17_reg_1063 <= {{m_axi_gmem0_0_RDATA[15:12]}};
        tmp_18_reg_1075 <= {{m_axi_gmem0_0_RDATA[19:16]}};
        tmp_19_reg_1087 <= {{m_axi_gmem0_0_RDATA[23:20]}};
        tmp_20_reg_1099 <= {{m_axi_gmem0_0_RDATA[27:24]}};
        tmp_s_reg_1111 <= {{m_axi_gmem0_0_RDATA[31:28]}};
        trunc_ln186_reg_1027 <= trunc_ln186_fu_615_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln182_fu_252_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((row_ok_load_2 == 1'd1) & (icmp_ln182_reg_1019_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_storemerge427_phi_fu_233_p4 = tmp_s_reg_1111;
    end else begin
        ap_phi_mux_storemerge427_phi_fu_233_p4 = ap_phi_reg_pp0_iter2_storemerge427_reg_229;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_sw = 4'd0;
    end else begin
        ap_sig_allocacmp_sw = sw_3_fu_208;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op101_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op101_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_0 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_0 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_0 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_0_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_1 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_1 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_1 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_10 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_10 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_10 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_10 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_10_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_11 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_11 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_11 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_11 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_11_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_12 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_12 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_12 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_12 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_12_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_13 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_13 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_13 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_13 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_13_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_14 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_14 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_14 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_14 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_14_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_15_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_16 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_16 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_16 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_16 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_16_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_16_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_17 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_17 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_17 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_17 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_17_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_17_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_18 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_18 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_18 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_18 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_18_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_18_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_19 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_19 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_19 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_19 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_19_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_19_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_1_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_2 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_2 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_2 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_20 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_20 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_20 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_20 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_20_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_20_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_21 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_21 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_21 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_21 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_21_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_21_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_568)) begin
            p_ZL9pw_in_buf_2_22 = 4'd0;
        end else if ((1'b1 == ap_condition_564)) begin
            p_ZL9pw_in_buf_2_22 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_22 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_22 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_22_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_22_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_23_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_23_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_24 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_24 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_24 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_24 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_24_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_24_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_25 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_25 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_25 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_25 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_25_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_25_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_26 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_26 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_26 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_26 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_26_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_26_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_27 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_27 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_27 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_27 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_27_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_27_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_28 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_28 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_28 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_28 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_28_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_28_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_29 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_29 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_29 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_29 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_29_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_29_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_2_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_3 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_3 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_3 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_575)) begin
            p_ZL9pw_in_buf_2_30 = 4'd0;
        end else if ((1'b1 == ap_condition_571)) begin
            p_ZL9pw_in_buf_2_30 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_30 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_30 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_30_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_30_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_31_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_31_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_32 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_32 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_32 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_32 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_32_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_32_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_33 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_33 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_33 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_33 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_33_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_33_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_34 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_34 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_34 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_34 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_34_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_34_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_35 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_35 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_35 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_35 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_35_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_35_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_36 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_36 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_36 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_36 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_36_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_36_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_37 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_37 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_37 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_37 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_37_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_37_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_582)) begin
            p_ZL9pw_in_buf_2_38 = 4'd0;
        end else if ((1'b1 == ap_condition_578)) begin
            p_ZL9pw_in_buf_2_38 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_38 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_38 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_38_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_38_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_39_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_39_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_3_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_4 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_4 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_4 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_40 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_40 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_40 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_40 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_40_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_40_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_41 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_41 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_41 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_41 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_41_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_41_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_42 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_42 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_42 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_42 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_42_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_42_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_43 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_43 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_43 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_43 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_43_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_43_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_44 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_44 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_44 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_44 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_44_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_44_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_45 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_45 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_45 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_45 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_45_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_45_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_589)) begin
            p_ZL9pw_in_buf_2_46 = 4'd0;
        end else if ((1'b1 == ap_condition_585)) begin
            p_ZL9pw_in_buf_2_46 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_46 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_46 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_46_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_46_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_47_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_47_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_48 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_48 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_48 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_48 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_48_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_48_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_49 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_49 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_49 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_49 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_49_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_49_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_4_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_5 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_5 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_5 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_50 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_50 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_50 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_50 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_50_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_50_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_51 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_51 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_51 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_51 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_51_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_51_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_52 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_52 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_52 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_52 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_52_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_52_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_53 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_53 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_53 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_53 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_53_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_53_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_596)) begin
            p_ZL9pw_in_buf_2_54 = 4'd0;
        end else if ((1'b1 == ap_condition_592)) begin
            p_ZL9pw_in_buf_2_54 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_54 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_54 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_54_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_54_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_55_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_55_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_56 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_56 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_56 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_56 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_56_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_56_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_57 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_57 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_57 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_57 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_57_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_57_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_58 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_58 = tmp_16_reg_1051;
        end else begin
            p_ZL9pw_in_buf_2_58 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_58 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_58_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_58_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_59 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_59 = tmp_17_reg_1063;
        end else begin
            p_ZL9pw_in_buf_2_59 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_59 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_59_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_59_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_5_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_554)) begin
            p_ZL9pw_in_buf_2_6 = 4'd0;
        end else if ((1'b1 == ap_condition_550)) begin
            p_ZL9pw_in_buf_2_6 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_6 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_60 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_60 = tmp_18_reg_1075;
        end else begin
            p_ZL9pw_in_buf_2_60 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_60 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_60_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_60_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_61 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_61 = tmp_19_reg_1087;
        end else begin
            p_ZL9pw_in_buf_2_61 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_61 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_61_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_61_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_603)) begin
            p_ZL9pw_in_buf_2_62 = 4'd0;
        end else if ((1'b1 == ap_condition_599)) begin
            p_ZL9pw_in_buf_2_62 = tmp_20_reg_1099;
        end else begin
            p_ZL9pw_in_buf_2_62 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_62 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_62_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_62_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_63_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_63_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_6_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9pw_in_buf_2_7_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_8 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_8 = trunc_ln186_reg_1027;
        end else begin
            p_ZL9pw_in_buf_2_8 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_8 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_8_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_grp0)) begin
        if ((1'b1 == ap_condition_561)) begin
            p_ZL9pw_in_buf_2_9 = 4'd0;
        end else if ((1'b1 == ap_condition_557)) begin
            p_ZL9pw_in_buf_2_9 = tmp_15_reg_1039;
        end else begin
            p_ZL9pw_in_buf_2_9 = 'bx;
        end
    end else begin
        p_ZL9pw_in_buf_2_9 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_ZL9pw_in_buf_2_9_ap_vld = 1'b1;
    end else begin
        p_ZL9pw_in_buf_2_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln182_fu_258_p2 = (ap_sig_allocacmp_sw + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1_grp1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_grp1 = ((ap_predicate_op101_read_state2 == 1'b1) & (m_axi_gmem0_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_condition_299 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_550 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_554 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_557 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd1) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_561 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_564 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd2) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_568 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_571 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd3) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_575 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_578 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd4) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_582 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_585 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd5) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_589 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_592 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd6) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_596 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_599 = ((row_ok_load_2 == 1'd1) & (trunc_ln182_reg_1023_pp0_iter1_reg == 3'd7) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_603 = ((row_ok_load_2_read_reg_1010 == 1'd0) & (trunc_ln182_reg_1023 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge427_reg_229 = 'bx;

always @ (*) begin
    ap_predicate_op101_read_state2 = ((row_ok_load_2 == 1'd1) & (icmp_ln182_reg_1019 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign icmp_ln182_fu_252_p2 = ((ap_sig_allocacmp_sw == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 32'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 4'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign p_ZL9pw_in_buf_2_15 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_23 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_31 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_39 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_47 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_55 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_63 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign p_ZL9pw_in_buf_2_7 = ap_phi_mux_storemerge427_phi_fu_233_p4;

assign row_ok_load_2_read_reg_1010 = row_ok_load_2;

assign trunc_ln182_fu_264_p1 = ap_sig_allocacmp_sw[2:0];

assign trunc_ln186_fu_615_p1 = m_axi_gmem0_0_RDATA[3:0];

endmodule //fastvit_ip_pwconv_worker_Pipeline_VITIS_LOOP_182_310
