// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps

module fastvit_ip_ashr_32ns_32ns_32_2_1(clk,ce,reset,din0, din1, dout);
parameter ID = 1;
parameter NUM_STAGE = 1;
parameter din0_WIDTH = 1;
parameter din1_WIDTH = 1;
parameter dout_WIDTH = 1;
parameter OP = 1;

input clk;
input ce;
input reset;

input [din0_WIDTH - 1 : 0] din0; 
input [din0_WIDTH - 1 : 0] din1; 
output [dout_WIDTH - 1 : 0] dout;

wire signed [dout_WIDTH - 1 : 0] tmp_product;


reg signed [dout_WIDTH - 1 : 0] buff0;











assign tmp_product = $signed(din0) >>> din1;






always @(posedge clk) begin
    if (reset) begin

        buff0 <= 0;






    end
    else begin 
        if (ce) begin
            buff0 <= tmp_product;





        end
    end
end




assign dout = buff0;






endmodule
