// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fastvit_ip_conv_worker_Pipeline_INIT_OUT_VITIS_LOOP_122_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        sub_ln101,
        shl_ln8,
        bias,
        p_ZL7out_buf_0_0_address0,
        p_ZL7out_buf_0_0_ce0,
        p_ZL7out_buf_0_0_we0,
        p_ZL7out_buf_0_0_d0,
        p_ZL7out_buf_0_1_address0,
        p_ZL7out_buf_0_1_ce0,
        p_ZL7out_buf_0_1_we0,
        p_ZL7out_buf_0_1_d0,
        p_ZL7out_buf_0_2_address0,
        p_ZL7out_buf_0_2_ce0,
        p_ZL7out_buf_0_2_we0,
        p_ZL7out_buf_0_2_d0,
        p_ZL7out_buf_0_3_address0,
        p_ZL7out_buf_0_3_ce0,
        p_ZL7out_buf_0_3_we0,
        p_ZL7out_buf_0_3_d0,
        p_ZL7out_buf_1_0_address0,
        p_ZL7out_buf_1_0_ce0,
        p_ZL7out_buf_1_0_we0,
        p_ZL7out_buf_1_0_d0,
        p_ZL7out_buf_1_1_address0,
        p_ZL7out_buf_1_1_ce0,
        p_ZL7out_buf_1_1_we0,
        p_ZL7out_buf_1_1_d0,
        p_ZL7out_buf_1_2_address0,
        p_ZL7out_buf_1_2_ce0,
        p_ZL7out_buf_1_2_we0,
        p_ZL7out_buf_1_2_d0,
        p_ZL7out_buf_1_3_address0,
        p_ZL7out_buf_1_3_ce0,
        p_ZL7out_buf_1_3_we0,
        p_ZL7out_buf_1_3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [31:0] m_axi_gmem2_0_WDATA;
output  [3:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [31:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [8:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [32:0] sub_ln101;
input  [30:0] shl_ln8;
input  [63:0] bias;
output  [1:0] p_ZL7out_buf_0_0_address0;
output   p_ZL7out_buf_0_0_ce0;
output   p_ZL7out_buf_0_0_we0;
output  [31:0] p_ZL7out_buf_0_0_d0;
output  [1:0] p_ZL7out_buf_0_1_address0;
output   p_ZL7out_buf_0_1_ce0;
output   p_ZL7out_buf_0_1_we0;
output  [31:0] p_ZL7out_buf_0_1_d0;
output  [1:0] p_ZL7out_buf_0_2_address0;
output   p_ZL7out_buf_0_2_ce0;
output   p_ZL7out_buf_0_2_we0;
output  [31:0] p_ZL7out_buf_0_2_d0;
output  [1:0] p_ZL7out_buf_0_3_address0;
output   p_ZL7out_buf_0_3_ce0;
output   p_ZL7out_buf_0_3_we0;
output  [31:0] p_ZL7out_buf_0_3_d0;
output  [1:0] p_ZL7out_buf_1_0_address0;
output   p_ZL7out_buf_1_0_ce0;
output   p_ZL7out_buf_1_0_we0;
output  [31:0] p_ZL7out_buf_1_0_d0;
output  [1:0] p_ZL7out_buf_1_1_address0;
output   p_ZL7out_buf_1_1_ce0;
output   p_ZL7out_buf_1_1_we0;
output  [31:0] p_ZL7out_buf_1_1_d0;
output  [1:0] p_ZL7out_buf_1_2_address0;
output   p_ZL7out_buf_1_2_ce0;
output   p_ZL7out_buf_1_2_we0;
output  [31:0] p_ZL7out_buf_1_2_d0;
output  [1:0] p_ZL7out_buf_1_3_address0;
output   p_ZL7out_buf_1_3_ce0;
output   p_ZL7out_buf_1_3_we0;
output  [31:0] p_ZL7out_buf_1_3_d0;

reg ap_idle;
reg m_axi_gmem2_0_ARVALID;
reg m_axi_gmem2_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln120_fu_260_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem2_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem2_blk_n_R;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln120_fu_295_p3;
reg   [2:0] select_ln120_reg_459;
reg   [2:0] select_ln120_reg_459_pp0_iter2_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter3_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter4_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter5_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter6_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter7_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter8_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter9_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter10_reg;
reg   [2:0] select_ln120_reg_459_pp0_iter11_reg;
wire   [1:0] select_ln120_1_fu_303_p3;
reg   [1:0] select_ln120_1_reg_464;
wire   [0:0] icmp_ln121_fu_315_p2;
reg   [0:0] icmp_ln121_reg_469;
wire   [0:0] cond_fu_320_p2;
reg   [0:0] cond_reg_474;
reg   [0:0] cond_reg_474_pp0_iter2_reg;
reg   [0:0] cond_reg_474_pp0_iter3_reg;
reg   [0:0] cond_reg_474_pp0_iter4_reg;
reg   [0:0] cond_reg_474_pp0_iter5_reg;
reg   [0:0] cond_reg_474_pp0_iter6_reg;
reg   [0:0] cond_reg_474_pp0_iter7_reg;
reg   [0:0] cond_reg_474_pp0_iter8_reg;
reg   [0:0] cond_reg_474_pp0_iter9_reg;
reg   [0:0] cond_reg_474_pp0_iter10_reg;
reg   [0:0] cond_reg_474_pp0_iter11_reg;
reg   [63:0] gmem2_addr_reg_478;
reg   [31:0] gmem2_addr_read_reg_484;
wire   [63:0] zext_ln122_fu_407_p1;
wire    ap_block_pp0_stage0_grp0;
wire  signed [63:0] p_cast42_cast_fu_397_p1;
reg   [2:0] r_fu_96;
wire   [2:0] add_ln122_fu_326_p2;
wire    ap_loop_init;
reg   [1:0] m_fu_100;
reg   [3:0] indvar_flatten_fu_104;
wire   [3:0] add_ln120_1_fu_266_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    p_ZL7out_buf_1_0_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    p_ZL7out_buf_1_0_ce0_local;
reg    p_ZL7out_buf_1_1_we0_local;
reg    p_ZL7out_buf_1_1_ce0_local;
reg    p_ZL7out_buf_1_2_we0_local;
reg    p_ZL7out_buf_1_2_ce0_local;
reg    p_ZL7out_buf_1_3_we0_local;
reg    p_ZL7out_buf_1_3_ce0_local;
reg    p_ZL7out_buf_0_0_we0_local;
reg    p_ZL7out_buf_0_0_ce0_local;
reg    p_ZL7out_buf_0_1_we0_local;
reg    p_ZL7out_buf_0_1_ce0_local;
reg    p_ZL7out_buf_0_2_we0_local;
reg    p_ZL7out_buf_0_2_ce0_local;
reg    p_ZL7out_buf_0_3_we0_local;
reg    p_ZL7out_buf_0_3_ce0_local;
wire   [0:0] icmp_ln122_fu_289_p2;
wire   [1:0] add_ln120_fu_283_p2;
wire   [32:0] zext_ln121_fu_311_p1;
wire   [0:0] trunc_ln121_fu_342_p1;
wire   [0:0] trunc_ln121_4_fu_350_p1;
wire   [0:0] and_ln121_fu_345_p2;
wire   [29:0] tmp_fu_359_p4;
wire   [0:0] or_ln121_fu_353_p2;
wire   [32:0] tmp_s_fu_368_p4;
wire   [63:0] p_cast49_fu_378_p1;
wire   [63:0] empty_fu_382_p2;
wire   [61:0] p_cast_fu_387_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 r_fu_96 = 3'd0;
#0 m_fu_100 = 2'd0;
#0 indvar_flatten_fu_104 = 4'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

fastvit_ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln120_fu_260_p2 == 1'd0))) begin
            indvar_flatten_fu_104 <= add_ln120_1_fu_266_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_104 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            m_fu_100 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            m_fu_100 <= select_ln120_1_fu_303_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_96 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            r_fu_96 <= add_ln122_fu_326_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        cond_reg_474 <= cond_fu_320_p2;
        icmp_ln121_reg_469 <= icmp_ln121_fu_315_p2;
        select_ln120_1_reg_464 <= select_ln120_1_fu_303_p3;
        select_ln120_reg_459 <= select_ln120_fu_295_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        cond_reg_474_pp0_iter10_reg <= cond_reg_474_pp0_iter9_reg;
        cond_reg_474_pp0_iter11_reg <= cond_reg_474_pp0_iter10_reg;
        cond_reg_474_pp0_iter2_reg <= cond_reg_474;
        cond_reg_474_pp0_iter3_reg <= cond_reg_474_pp0_iter2_reg;
        cond_reg_474_pp0_iter4_reg <= cond_reg_474_pp0_iter3_reg;
        cond_reg_474_pp0_iter5_reg <= cond_reg_474_pp0_iter4_reg;
        cond_reg_474_pp0_iter6_reg <= cond_reg_474_pp0_iter5_reg;
        cond_reg_474_pp0_iter7_reg <= cond_reg_474_pp0_iter6_reg;
        cond_reg_474_pp0_iter8_reg <= cond_reg_474_pp0_iter7_reg;
        cond_reg_474_pp0_iter9_reg <= cond_reg_474_pp0_iter8_reg;
        gmem2_addr_read_reg_484 <= m_axi_gmem2_0_RDATA;
        gmem2_addr_reg_478 <= p_cast42_cast_fu_397_p1;
        select_ln120_reg_459_pp0_iter10_reg <= select_ln120_reg_459_pp0_iter9_reg;
        select_ln120_reg_459_pp0_iter11_reg <= select_ln120_reg_459_pp0_iter10_reg;
        select_ln120_reg_459_pp0_iter2_reg <= select_ln120_reg_459;
        select_ln120_reg_459_pp0_iter3_reg <= select_ln120_reg_459_pp0_iter2_reg;
        select_ln120_reg_459_pp0_iter4_reg <= select_ln120_reg_459_pp0_iter3_reg;
        select_ln120_reg_459_pp0_iter5_reg <= select_ln120_reg_459_pp0_iter4_reg;
        select_ln120_reg_459_pp0_iter6_reg <= select_ln120_reg_459_pp0_iter5_reg;
        select_ln120_reg_459_pp0_iter7_reg <= select_ln120_reg_459_pp0_iter6_reg;
        select_ln120_reg_459_pp0_iter8_reg <= select_ln120_reg_459_pp0_iter7_reg;
        select_ln120_reg_459_pp0_iter9_reg <= select_ln120_reg_459_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln120_fu_260_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_104;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem2_blk_n_AR = m_axi_gmem2_0_ARREADY;
    end else begin
        gmem2_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem2_blk_n_R = m_axi_gmem2_0_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem2_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem2_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem2_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_0_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_1_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_2_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_3_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_0_3_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_0_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_0_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_1_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_2_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_3_ce0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (cond_reg_474_pp0_iter11_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZL7out_buf_1_3_we0_local = 1'b1;
    end else begin
        p_ZL7out_buf_1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln120_1_fu_266_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln120_fu_283_p2 = (m_fu_100 + 2'd1);

assign add_ln122_fu_326_p2 = (select_ln120_fu_295_p3 + 3'd1);

assign and_ln121_fu_345_p2 = (trunc_ln121_fu_342_p1 & icmp_ln121_reg_469);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem2_0_RVALID == 1'b0)) | ((m_axi_gmem2_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cond_fu_320_p2 = ((select_ln120_1_fu_303_p3 == 2'd0) ? 1'b1 : 1'b0);

assign empty_fu_382_p2 = (p_cast49_fu_378_p1 + bias);

assign icmp_ln120_fu_260_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_315_p2 = (($signed(zext_ln121_fu_311_p1) < $signed(sub_ln101)) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_289_p2 = ((r_fu_96 == 3'd4) ? 1'b1 : 1'b0);

assign m_axi_gmem2_0_ARADDR = gmem2_addr_reg_478;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 64'd1;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 32'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 4'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign or_ln121_fu_353_p2 = (trunc_ln121_4_fu_350_p1 | and_ln121_fu_345_p2);

assign p_ZL7out_buf_0_0_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_0_0_ce0 = p_ZL7out_buf_0_0_ce0_local;

assign p_ZL7out_buf_0_0_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_0_0_we0 = p_ZL7out_buf_0_0_we0_local;

assign p_ZL7out_buf_0_1_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_0_1_ce0 = p_ZL7out_buf_0_1_ce0_local;

assign p_ZL7out_buf_0_1_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_0_1_we0 = p_ZL7out_buf_0_1_we0_local;

assign p_ZL7out_buf_0_2_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_0_2_ce0 = p_ZL7out_buf_0_2_ce0_local;

assign p_ZL7out_buf_0_2_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_0_2_we0 = p_ZL7out_buf_0_2_we0_local;

assign p_ZL7out_buf_0_3_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_0_3_ce0 = p_ZL7out_buf_0_3_ce0_local;

assign p_ZL7out_buf_0_3_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_0_3_we0 = p_ZL7out_buf_0_3_we0_local;

assign p_ZL7out_buf_1_0_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_1_0_ce0 = p_ZL7out_buf_1_0_ce0_local;

assign p_ZL7out_buf_1_0_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_1_0_we0 = p_ZL7out_buf_1_0_we0_local;

assign p_ZL7out_buf_1_1_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_1_1_ce0 = p_ZL7out_buf_1_1_ce0_local;

assign p_ZL7out_buf_1_1_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_1_1_we0 = p_ZL7out_buf_1_1_we0_local;

assign p_ZL7out_buf_1_2_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_1_2_ce0 = p_ZL7out_buf_1_2_ce0_local;

assign p_ZL7out_buf_1_2_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_1_2_we0 = p_ZL7out_buf_1_2_we0_local;

assign p_ZL7out_buf_1_3_address0 = zext_ln122_fu_407_p1;

assign p_ZL7out_buf_1_3_ce0 = p_ZL7out_buf_1_3_ce0_local;

assign p_ZL7out_buf_1_3_d0 = gmem2_addr_read_reg_484;

assign p_ZL7out_buf_1_3_we0 = p_ZL7out_buf_1_3_we0_local;

assign p_cast42_cast_fu_397_p1 = $signed(p_cast_fu_387_p4);

assign p_cast49_fu_378_p1 = tmp_s_fu_368_p4;

assign p_cast_fu_387_p4 = {{empty_fu_382_p2[63:2]}};

assign select_ln120_1_fu_303_p3 = ((icmp_ln122_fu_289_p2[0:0] == 1'b1) ? add_ln120_fu_283_p2 : m_fu_100);

assign select_ln120_fu_295_p3 = ((icmp_ln122_fu_289_p2[0:0] == 1'b1) ? 3'd0 : r_fu_96);

assign tmp_fu_359_p4 = {{shl_ln8[30:1]}};

assign tmp_s_fu_368_p4 = {{{tmp_fu_359_p4}, {or_ln121_fu_353_p2}}, {2'd0}};

assign trunc_ln121_4_fu_350_p1 = shl_ln8[0:0];

assign trunc_ln121_fu_342_p1 = select_ln120_1_reg_464[0:0];

assign zext_ln121_fu_311_p1 = select_ln120_1_fu_303_p3;

assign zext_ln122_fu_407_p1 = select_ln120_reg_459_pp0_iter11_reg;

endmodule //fastvit_ip_conv_worker_Pipeline_INIT_OUT_VITIS_LOOP_122_1
