// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fastvit_ip_dwconv_preload_channel3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        feat_in,
        ch,
        Win,
        Hin,
        p_ZL9ch_in_buf_0_address0,
        p_ZL9ch_in_buf_0_ce0,
        p_ZL9ch_in_buf_0_we0,
        p_ZL9ch_in_buf_0_d0,
        p_ZL9ch_in_buf_1_address0,
        p_ZL9ch_in_buf_1_ce0,
        p_ZL9ch_in_buf_1_we0,
        p_ZL9ch_in_buf_1_d0,
        p_ZL9ch_in_buf_10_address0,
        p_ZL9ch_in_buf_10_ce0,
        p_ZL9ch_in_buf_10_we0,
        p_ZL9ch_in_buf_10_d0,
        p_ZL9ch_in_buf_11_address0,
        p_ZL9ch_in_buf_11_ce0,
        p_ZL9ch_in_buf_11_we0,
        p_ZL9ch_in_buf_11_d0,
        p_ZL9ch_in_buf_12_address0,
        p_ZL9ch_in_buf_12_ce0,
        p_ZL9ch_in_buf_12_we0,
        p_ZL9ch_in_buf_12_d0,
        p_ZL9ch_in_buf_13_address0,
        p_ZL9ch_in_buf_13_ce0,
        p_ZL9ch_in_buf_13_we0,
        p_ZL9ch_in_buf_13_d0,
        p_ZL9ch_in_buf_14_address0,
        p_ZL9ch_in_buf_14_ce0,
        p_ZL9ch_in_buf_14_we0,
        p_ZL9ch_in_buf_14_d0,
        p_ZL9ch_in_buf_15_address0,
        p_ZL9ch_in_buf_15_ce0,
        p_ZL9ch_in_buf_15_we0,
        p_ZL9ch_in_buf_15_d0,
        p_ZL9ch_in_buf_2_address0,
        p_ZL9ch_in_buf_2_ce0,
        p_ZL9ch_in_buf_2_we0,
        p_ZL9ch_in_buf_2_d0,
        p_ZL9ch_in_buf_3_address0,
        p_ZL9ch_in_buf_3_ce0,
        p_ZL9ch_in_buf_3_we0,
        p_ZL9ch_in_buf_3_d0,
        p_ZL9ch_in_buf_4_address0,
        p_ZL9ch_in_buf_4_ce0,
        p_ZL9ch_in_buf_4_we0,
        p_ZL9ch_in_buf_4_d0,
        p_ZL9ch_in_buf_5_address0,
        p_ZL9ch_in_buf_5_ce0,
        p_ZL9ch_in_buf_5_we0,
        p_ZL9ch_in_buf_5_d0,
        p_ZL9ch_in_buf_6_address0,
        p_ZL9ch_in_buf_6_ce0,
        p_ZL9ch_in_buf_6_we0,
        p_ZL9ch_in_buf_6_d0,
        p_ZL9ch_in_buf_7_address0,
        p_ZL9ch_in_buf_7_ce0,
        p_ZL9ch_in_buf_7_we0,
        p_ZL9ch_in_buf_7_d0,
        p_ZL9ch_in_buf_8_address0,
        p_ZL9ch_in_buf_8_ce0,
        p_ZL9ch_in_buf_8_we0,
        p_ZL9ch_in_buf_8_d0,
        p_ZL9ch_in_buf_9_address0,
        p_ZL9ch_in_buf_9_ce0,
        p_ZL9ch_in_buf_9_we0,
        p_ZL9ch_in_buf_9_d0
);

parameter    ap_ST_fsm_state1 = 84'd1;
parameter    ap_ST_fsm_state2 = 84'd2;
parameter    ap_ST_fsm_state3 = 84'd4;
parameter    ap_ST_fsm_state4 = 84'd8;
parameter    ap_ST_fsm_state5 = 84'd16;
parameter    ap_ST_fsm_state6 = 84'd32;
parameter    ap_ST_fsm_state7 = 84'd64;
parameter    ap_ST_fsm_state8 = 84'd128;
parameter    ap_ST_fsm_state9 = 84'd256;
parameter    ap_ST_fsm_state10 = 84'd512;
parameter    ap_ST_fsm_state11 = 84'd1024;
parameter    ap_ST_fsm_state12 = 84'd2048;
parameter    ap_ST_fsm_state13 = 84'd4096;
parameter    ap_ST_fsm_state14 = 84'd8192;
parameter    ap_ST_fsm_state15 = 84'd16384;
parameter    ap_ST_fsm_state16 = 84'd32768;
parameter    ap_ST_fsm_state17 = 84'd65536;
parameter    ap_ST_fsm_state18 = 84'd131072;
parameter    ap_ST_fsm_state19 = 84'd262144;
parameter    ap_ST_fsm_state20 = 84'd524288;
parameter    ap_ST_fsm_state21 = 84'd1048576;
parameter    ap_ST_fsm_state22 = 84'd2097152;
parameter    ap_ST_fsm_state23 = 84'd4194304;
parameter    ap_ST_fsm_state24 = 84'd8388608;
parameter    ap_ST_fsm_state25 = 84'd16777216;
parameter    ap_ST_fsm_state26 = 84'd33554432;
parameter    ap_ST_fsm_state27 = 84'd67108864;
parameter    ap_ST_fsm_state28 = 84'd134217728;
parameter    ap_ST_fsm_state29 = 84'd268435456;
parameter    ap_ST_fsm_state30 = 84'd536870912;
parameter    ap_ST_fsm_state31 = 84'd1073741824;
parameter    ap_ST_fsm_state32 = 84'd2147483648;
parameter    ap_ST_fsm_state33 = 84'd4294967296;
parameter    ap_ST_fsm_state34 = 84'd8589934592;
parameter    ap_ST_fsm_state35 = 84'd17179869184;
parameter    ap_ST_fsm_state36 = 84'd34359738368;
parameter    ap_ST_fsm_state37 = 84'd68719476736;
parameter    ap_ST_fsm_state38 = 84'd137438953472;
parameter    ap_ST_fsm_state39 = 84'd274877906944;
parameter    ap_ST_fsm_state40 = 84'd549755813888;
parameter    ap_ST_fsm_state41 = 84'd1099511627776;
parameter    ap_ST_fsm_state42 = 84'd2199023255552;
parameter    ap_ST_fsm_state43 = 84'd4398046511104;
parameter    ap_ST_fsm_state44 = 84'd8796093022208;
parameter    ap_ST_fsm_state45 = 84'd17592186044416;
parameter    ap_ST_fsm_state46 = 84'd35184372088832;
parameter    ap_ST_fsm_state47 = 84'd70368744177664;
parameter    ap_ST_fsm_state48 = 84'd140737488355328;
parameter    ap_ST_fsm_state49 = 84'd281474976710656;
parameter    ap_ST_fsm_state50 = 84'd562949953421312;
parameter    ap_ST_fsm_state51 = 84'd1125899906842624;
parameter    ap_ST_fsm_state52 = 84'd2251799813685248;
parameter    ap_ST_fsm_state53 = 84'd4503599627370496;
parameter    ap_ST_fsm_state54 = 84'd9007199254740992;
parameter    ap_ST_fsm_state55 = 84'd18014398509481984;
parameter    ap_ST_fsm_state56 = 84'd36028797018963968;
parameter    ap_ST_fsm_state57 = 84'd72057594037927936;
parameter    ap_ST_fsm_state58 = 84'd144115188075855872;
parameter    ap_ST_fsm_state59 = 84'd288230376151711744;
parameter    ap_ST_fsm_state60 = 84'd576460752303423488;
parameter    ap_ST_fsm_state61 = 84'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 84'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 84'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 84'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 84'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 84'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 84'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 84'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 84'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 84'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 84'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 84'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 84'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 84'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 84'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 84'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 84'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 84'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 84'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 84'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 84'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 84'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 84'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 84'd9671406556917033397649408;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [31:0] m_axi_gmem0_0_WDATA;
output  [3:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [31:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [63:0] feat_in;
input  [9:0] ch;
input  [31:0] Win;
input  [31:0] Hin;
output  [7:0] p_ZL9ch_in_buf_0_address0;
output   p_ZL9ch_in_buf_0_ce0;
output   p_ZL9ch_in_buf_0_we0;
output  [3:0] p_ZL9ch_in_buf_0_d0;
output  [7:0] p_ZL9ch_in_buf_1_address0;
output   p_ZL9ch_in_buf_1_ce0;
output   p_ZL9ch_in_buf_1_we0;
output  [3:0] p_ZL9ch_in_buf_1_d0;
output  [7:0] p_ZL9ch_in_buf_10_address0;
output   p_ZL9ch_in_buf_10_ce0;
output   p_ZL9ch_in_buf_10_we0;
output  [3:0] p_ZL9ch_in_buf_10_d0;
output  [7:0] p_ZL9ch_in_buf_11_address0;
output   p_ZL9ch_in_buf_11_ce0;
output   p_ZL9ch_in_buf_11_we0;
output  [3:0] p_ZL9ch_in_buf_11_d0;
output  [7:0] p_ZL9ch_in_buf_12_address0;
output   p_ZL9ch_in_buf_12_ce0;
output   p_ZL9ch_in_buf_12_we0;
output  [3:0] p_ZL9ch_in_buf_12_d0;
output  [7:0] p_ZL9ch_in_buf_13_address0;
output   p_ZL9ch_in_buf_13_ce0;
output   p_ZL9ch_in_buf_13_we0;
output  [3:0] p_ZL9ch_in_buf_13_d0;
output  [7:0] p_ZL9ch_in_buf_14_address0;
output   p_ZL9ch_in_buf_14_ce0;
output   p_ZL9ch_in_buf_14_we0;
output  [3:0] p_ZL9ch_in_buf_14_d0;
output  [7:0] p_ZL9ch_in_buf_15_address0;
output   p_ZL9ch_in_buf_15_ce0;
output   p_ZL9ch_in_buf_15_we0;
output  [3:0] p_ZL9ch_in_buf_15_d0;
output  [7:0] p_ZL9ch_in_buf_2_address0;
output   p_ZL9ch_in_buf_2_ce0;
output   p_ZL9ch_in_buf_2_we0;
output  [3:0] p_ZL9ch_in_buf_2_d0;
output  [7:0] p_ZL9ch_in_buf_3_address0;
output   p_ZL9ch_in_buf_3_ce0;
output   p_ZL9ch_in_buf_3_we0;
output  [3:0] p_ZL9ch_in_buf_3_d0;
output  [7:0] p_ZL9ch_in_buf_4_address0;
output   p_ZL9ch_in_buf_4_ce0;
output   p_ZL9ch_in_buf_4_we0;
output  [3:0] p_ZL9ch_in_buf_4_d0;
output  [7:0] p_ZL9ch_in_buf_5_address0;
output   p_ZL9ch_in_buf_5_ce0;
output   p_ZL9ch_in_buf_5_we0;
output  [3:0] p_ZL9ch_in_buf_5_d0;
output  [7:0] p_ZL9ch_in_buf_6_address0;
output   p_ZL9ch_in_buf_6_ce0;
output   p_ZL9ch_in_buf_6_we0;
output  [3:0] p_ZL9ch_in_buf_6_d0;
output  [7:0] p_ZL9ch_in_buf_7_address0;
output   p_ZL9ch_in_buf_7_ce0;
output   p_ZL9ch_in_buf_7_we0;
output  [3:0] p_ZL9ch_in_buf_7_d0;
output  [7:0] p_ZL9ch_in_buf_8_address0;
output   p_ZL9ch_in_buf_8_ce0;
output   p_ZL9ch_in_buf_8_we0;
output  [3:0] p_ZL9ch_in_buf_8_d0;
output  [7:0] p_ZL9ch_in_buf_9_address0;
output   p_ZL9ch_in_buf_9_ce0;
output   p_ZL9ch_in_buf_9_we0;
output  [3:0] p_ZL9ch_in_buf_9_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_0_ARVALID;
reg[63:0] m_axi_gmem0_0_ARADDR;
reg[0:0] m_axi_gmem0_0_ARID;
reg[31:0] m_axi_gmem0_0_ARLEN;
reg[2:0] m_axi_gmem0_0_ARSIZE;
reg[1:0] m_axi_gmem0_0_ARBURST;
reg[1:0] m_axi_gmem0_0_ARLOCK;
reg[3:0] m_axi_gmem0_0_ARCACHE;
reg[2:0] m_axi_gmem0_0_ARPROT;
reg[3:0] m_axi_gmem0_0_ARQOS;
reg[3:0] m_axi_gmem0_0_ARREGION;
reg[0:0] m_axi_gmem0_0_ARUSER;
reg m_axi_gmem0_0_RREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [83:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state12;
reg    ap_block_state1;
reg  signed [28:0] hw_in_words_reg_312;
wire    ap_CS_fsm_state5;
reg   [27:0] wide_trip_count_i_i_reg_319;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_210_p2;
reg   [31:0] mul_i_i_reg_334;
wire    ap_CS_fsm_state10;
reg   [61:0] trunc_ln_reg_339;
wire    ap_CS_fsm_state11;
wire   [27:0] empty_fu_281_p3;
reg   [27:0] empty_reg_345;
wire   [63:0] zext_ln85_fu_298_p1;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_idle;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_ready;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWID;
wire   [31:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWUSER;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WVALID;
wire   [31:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WDATA;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WSTRB;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WID;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WUSER;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARID;
wire   [31:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARUSER;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_RREADY;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_BREADY;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_d0;
wire   [7:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_address0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_ce0;
wire    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_we0;
wire   [3:0] grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_d0;
reg    grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg;
wire    ap_CS_fsm_state83;
wire    ap_CS_fsm_state84;
wire  signed [63:0] sext_ln85_1_fu_288_p1;
wire   [9:0] grp_fu_210_p1;
wire   [31:0] grp_fu_214_p2;
wire   [33:0] shl_ln_fu_254_p3;
wire  signed [63:0] sext_ln85_fu_261_p1;
wire   [63:0] add_ln85_fu_265_p2;
wire   [0:0] icmp_ln85_fu_249_p2;
reg    grp_fu_214_ce;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [83:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
reg    ap_ST_fsm_state84_blk;
wire   [31:0] grp_fu_210_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 84'd1;
#0 grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg = 1'b0;
end

fastvit_ip_dwconv_preload_channel3_Pipeline_PRELOAD_IN grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start),
    .ap_done(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done),
    .ap_idle(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_idle),
    .ap_ready(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(m_axi_gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(m_axi_gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(m_axi_gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(m_axi_gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(m_axi_gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(m_axi_gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(m_axi_gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(m_axi_gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .hw_in_words(hw_in_words_reg_312),
    .sext_ln85_1(trunc_ln_reg_339),
    .p_ZL9ch_in_buf_15_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_address0),
    .p_ZL9ch_in_buf_15_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_ce0),
    .p_ZL9ch_in_buf_15_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_we0),
    .p_ZL9ch_in_buf_15_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_d0),
    .p_ZL9ch_in_buf_14_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_address0),
    .p_ZL9ch_in_buf_14_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_ce0),
    .p_ZL9ch_in_buf_14_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_we0),
    .p_ZL9ch_in_buf_14_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_d0),
    .p_ZL9ch_in_buf_13_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_address0),
    .p_ZL9ch_in_buf_13_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_ce0),
    .p_ZL9ch_in_buf_13_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_we0),
    .p_ZL9ch_in_buf_13_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_d0),
    .p_ZL9ch_in_buf_12_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_address0),
    .p_ZL9ch_in_buf_12_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_ce0),
    .p_ZL9ch_in_buf_12_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_we0),
    .p_ZL9ch_in_buf_12_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_d0),
    .p_ZL9ch_in_buf_11_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_address0),
    .p_ZL9ch_in_buf_11_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_ce0),
    .p_ZL9ch_in_buf_11_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_we0),
    .p_ZL9ch_in_buf_11_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_d0),
    .p_ZL9ch_in_buf_10_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_address0),
    .p_ZL9ch_in_buf_10_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_ce0),
    .p_ZL9ch_in_buf_10_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_we0),
    .p_ZL9ch_in_buf_10_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_d0),
    .p_ZL9ch_in_buf_9_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_address0),
    .p_ZL9ch_in_buf_9_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_ce0),
    .p_ZL9ch_in_buf_9_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_we0),
    .p_ZL9ch_in_buf_9_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_d0),
    .p_ZL9ch_in_buf_8_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_address0),
    .p_ZL9ch_in_buf_8_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_ce0),
    .p_ZL9ch_in_buf_8_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_we0),
    .p_ZL9ch_in_buf_8_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_d0),
    .p_ZL9ch_in_buf_7_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_address0),
    .p_ZL9ch_in_buf_7_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_ce0),
    .p_ZL9ch_in_buf_7_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_we0),
    .p_ZL9ch_in_buf_7_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_d0),
    .p_ZL9ch_in_buf_6_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_address0),
    .p_ZL9ch_in_buf_6_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_ce0),
    .p_ZL9ch_in_buf_6_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_we0),
    .p_ZL9ch_in_buf_6_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_d0),
    .p_ZL9ch_in_buf_5_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_address0),
    .p_ZL9ch_in_buf_5_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_ce0),
    .p_ZL9ch_in_buf_5_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_we0),
    .p_ZL9ch_in_buf_5_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_d0),
    .p_ZL9ch_in_buf_4_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_address0),
    .p_ZL9ch_in_buf_4_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_ce0),
    .p_ZL9ch_in_buf_4_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_we0),
    .p_ZL9ch_in_buf_4_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_d0),
    .p_ZL9ch_in_buf_3_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_address0),
    .p_ZL9ch_in_buf_3_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_ce0),
    .p_ZL9ch_in_buf_3_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_we0),
    .p_ZL9ch_in_buf_3_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_d0),
    .p_ZL9ch_in_buf_2_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_address0),
    .p_ZL9ch_in_buf_2_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_ce0),
    .p_ZL9ch_in_buf_2_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_we0),
    .p_ZL9ch_in_buf_2_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_d0),
    .p_ZL9ch_in_buf_1_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_address0),
    .p_ZL9ch_in_buf_1_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_ce0),
    .p_ZL9ch_in_buf_1_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_we0),
    .p_ZL9ch_in_buf_1_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_d0),
    .p_ZL9ch_in_buf_0_address0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_address0),
    .p_ZL9ch_in_buf_0_ce0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_ce0),
    .p_ZL9ch_in_buf_0_we0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_we0),
    .p_ZL9ch_in_buf_0_d0(grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_d0)
);

fastvit_ip_mul_29s_10ns_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 32 ))
mul_29s_10ns_32_5_1_U1626(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(hw_in_words_reg_312),
    .din1(grp_fu_210_p1),
    .ce(1'b1),
    .dout(grp_fu_210_p2)
);

fastvit_ip_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U1627(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Win),
    .din1(Hin),
    .ce(grp_fu_214_ce),
    .dout(grp_fu_214_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state83)) begin
            grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg <= 1'b1;
        end else if ((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_ready == 1'b1)) begin
            grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        empty_reg_345 <= empty_fu_281_p3;
        trunc_ln_reg_339 <= {{add_ln85_fu_265_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hw_in_words_reg_312 <= {{grp_fu_214_p2[31:3]}};
        wide_trip_count_i_i_reg_319 <= {{grp_fu_214_p2[30:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        mul_i_i_reg_334 <= grp_fu_210_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

always @ (*) begin
    if ((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done == 1'b0)) begin
        ap_ST_fsm_state84_blk = 1'b1;
    end else begin
        ap_ST_fsm_state84_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gmem0_blk_n_AR = m_axi_gmem0_0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_214_ce = 1'b1;
    end else begin
        grp_fu_214_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (m_axi_gmem0_0_ARREADY == 1'b1))) begin
        m_axi_gmem0_0_ARADDR = sext_ln85_1_fu_288_p1;
    end else if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARADDR = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARADDR;
    end else begin
        m_axi_gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARBURST = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARBURST;
    end else begin
        m_axi_gmem0_0_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARCACHE = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARCACHE;
    end else begin
        m_axi_gmem0_0_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARID = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARID;
    end else begin
        m_axi_gmem0_0_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (m_axi_gmem0_0_ARREADY == 1'b1))) begin
        m_axi_gmem0_0_ARLEN = zext_ln85_fu_298_p1;
    end else if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARLEN = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLEN;
    end else begin
        m_axi_gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARLOCK = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARLOCK;
    end else begin
        m_axi_gmem0_0_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARPROT = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARPROT;
    end else begin
        m_axi_gmem0_0_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARQOS = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARQOS;
    end else begin
        m_axi_gmem0_0_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARREGION = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARREGION;
    end else begin
        m_axi_gmem0_0_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARSIZE = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARSIZE;
    end else begin
        m_axi_gmem0_0_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARUSER = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARUSER;
    end else begin
        m_axi_gmem0_0_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) & (m_axi_gmem0_0_ARREADY == 1'b1))) begin
        m_axi_gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_ARVALID = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_ARVALID;
    end else begin
        m_axi_gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        m_axi_gmem0_0_RREADY = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_m_axi_gmem0_0_RREADY;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (m_axi_gmem0_0_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            if (((grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state84;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_265_p2 = ($signed(sext_ln85_fu_261_p1) + $signed(feat_in));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign empty_fu_281_p3 = ((icmp_ln85_fu_249_p2[0:0] == 1'b1) ? wide_trip_count_i_i_reg_319 : 28'd0);

assign grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_ap_start_reg;

assign grp_fu_210_p1 = grp_fu_210_p10;

assign grp_fu_210_p10 = ch;

assign icmp_ln85_fu_249_p2 = (($signed(hw_in_words_reg_312) > $signed(29'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 32'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 4'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign p_ZL9ch_in_buf_0_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_address0;

assign p_ZL9ch_in_buf_0_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_ce0;

assign p_ZL9ch_in_buf_0_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_d0;

assign p_ZL9ch_in_buf_0_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_0_we0;

assign p_ZL9ch_in_buf_10_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_address0;

assign p_ZL9ch_in_buf_10_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_ce0;

assign p_ZL9ch_in_buf_10_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_d0;

assign p_ZL9ch_in_buf_10_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_10_we0;

assign p_ZL9ch_in_buf_11_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_address0;

assign p_ZL9ch_in_buf_11_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_ce0;

assign p_ZL9ch_in_buf_11_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_d0;

assign p_ZL9ch_in_buf_11_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_11_we0;

assign p_ZL9ch_in_buf_12_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_address0;

assign p_ZL9ch_in_buf_12_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_ce0;

assign p_ZL9ch_in_buf_12_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_d0;

assign p_ZL9ch_in_buf_12_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_12_we0;

assign p_ZL9ch_in_buf_13_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_address0;

assign p_ZL9ch_in_buf_13_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_ce0;

assign p_ZL9ch_in_buf_13_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_d0;

assign p_ZL9ch_in_buf_13_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_13_we0;

assign p_ZL9ch_in_buf_14_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_address0;

assign p_ZL9ch_in_buf_14_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_ce0;

assign p_ZL9ch_in_buf_14_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_d0;

assign p_ZL9ch_in_buf_14_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_14_we0;

assign p_ZL9ch_in_buf_15_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_address0;

assign p_ZL9ch_in_buf_15_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_ce0;

assign p_ZL9ch_in_buf_15_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_d0;

assign p_ZL9ch_in_buf_15_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_15_we0;

assign p_ZL9ch_in_buf_1_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_address0;

assign p_ZL9ch_in_buf_1_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_ce0;

assign p_ZL9ch_in_buf_1_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_d0;

assign p_ZL9ch_in_buf_1_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_1_we0;

assign p_ZL9ch_in_buf_2_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_address0;

assign p_ZL9ch_in_buf_2_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_ce0;

assign p_ZL9ch_in_buf_2_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_d0;

assign p_ZL9ch_in_buf_2_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_2_we0;

assign p_ZL9ch_in_buf_3_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_address0;

assign p_ZL9ch_in_buf_3_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_ce0;

assign p_ZL9ch_in_buf_3_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_d0;

assign p_ZL9ch_in_buf_3_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_3_we0;

assign p_ZL9ch_in_buf_4_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_address0;

assign p_ZL9ch_in_buf_4_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_ce0;

assign p_ZL9ch_in_buf_4_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_d0;

assign p_ZL9ch_in_buf_4_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_4_we0;

assign p_ZL9ch_in_buf_5_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_address0;

assign p_ZL9ch_in_buf_5_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_ce0;

assign p_ZL9ch_in_buf_5_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_d0;

assign p_ZL9ch_in_buf_5_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_5_we0;

assign p_ZL9ch_in_buf_6_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_address0;

assign p_ZL9ch_in_buf_6_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_ce0;

assign p_ZL9ch_in_buf_6_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_d0;

assign p_ZL9ch_in_buf_6_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_6_we0;

assign p_ZL9ch_in_buf_7_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_address0;

assign p_ZL9ch_in_buf_7_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_ce0;

assign p_ZL9ch_in_buf_7_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_d0;

assign p_ZL9ch_in_buf_7_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_7_we0;

assign p_ZL9ch_in_buf_8_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_address0;

assign p_ZL9ch_in_buf_8_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_ce0;

assign p_ZL9ch_in_buf_8_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_d0;

assign p_ZL9ch_in_buf_8_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_8_we0;

assign p_ZL9ch_in_buf_9_address0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_address0;

assign p_ZL9ch_in_buf_9_ce0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_ce0;

assign p_ZL9ch_in_buf_9_d0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_d0;

assign p_ZL9ch_in_buf_9_we0 = grp_dwconv_preload_channel3_Pipeline_PRELOAD_IN_fu_170_p_ZL9ch_in_buf_9_we0;

assign sext_ln85_1_fu_288_p1 = $signed(trunc_ln_reg_339);

assign sext_ln85_fu_261_p1 = $signed(shl_ln_fu_254_p3);

assign shl_ln_fu_254_p3 = {{mul_i_i_reg_334}, {2'd0}};

assign zext_ln85_fu_298_p1 = empty_reg_345;

endmodule //fastvit_ip_dwconv_preload_channel3
