// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fastvit_ip_dwconv_process_channel4_Pipeline_LOAD_DW_IN_ROWBASE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_80,
        empty,
        row_base_addr_address0,
        row_base_addr_ce0,
        row_base_addr_we0,
        row_base_addr_d0,
        in_tile_h,
        row_in_tile_address0,
        row_in_tile_ce0,
        row_in_tile_we0,
        row_in_tile_d0,
        Hin,
        row_in_bounds_address0,
        row_in_bounds_ce0,
        row_in_bounds_we0,
        row_in_bounds_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] empty_80;
input  [11:0] empty;
output  [3:0] row_base_addr_address0;
output   row_base_addr_ce0;
output   row_base_addr_we0;
output  [11:0] row_base_addr_d0;
input  [31:0] in_tile_h;
output  [3:0] row_in_tile_address0;
output   row_in_tile_ce0;
output   row_in_tile_we0;
output  [0:0] row_in_tile_d0;
input  [31:0] Hin;
output  [3:0] row_in_bounds_address0;
output   row_in_bounds_ce0;
output   row_in_bounds_we0;
output  [0:0] row_in_bounds_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln202_fu_123_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] r_60_reg_212;
wire   [31:0] zext_ln202_fu_135_p1;
reg   [31:0] zext_ln202_reg_221;
wire   [31:0] in_r_fu_139_p2;
reg   [31:0] in_r_reg_226;
wire  signed [11:0] trunc_ln204_fu_145_p1;
reg  signed [11:0] trunc_ln204_reg_232;
wire   [63:0] zext_ln202_1_fu_154_p1;
reg   [63:0] zext_ln202_1_reg_237;
reg   [63:0] zext_ln202_1_reg_237_pp0_iter2_reg;
wire   [0:0] and_ln207_fu_184_p2;
reg   [0:0] and_ln207_reg_243;
wire   [11:0] grp_fu_158_p2;
reg   [11:0] mul_ln205_reg_248;
wire    ap_block_pp0_stage0;
reg   [3:0] r_fu_48;
wire   [3:0] r_61_fu_129_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_r_60;
reg    row_in_tile_we0_local;
wire   [0:0] icmp_ln206_fu_162_p2;
reg    row_in_tile_ce0_local;
reg    row_in_bounds_we0_local;
reg    row_in_bounds_ce0_local;
reg    row_base_addr_we0_local;
reg    row_base_addr_ce0_local;
wire   [0:0] tmp_59_fu_167_p3;
wire   [0:0] icmp_ln207_fu_180_p2;
wire   [0:0] xor_ln207_fu_174_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 r_fu_48 = 4'd0;
#0 ap_done_reg = 1'b0;
end

fastvit_ip_mul_12s_12s_12_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
mul_12s_12s_12_2_1_U1650(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln204_reg_232),
    .din1(empty),
    .ce(1'b1),
    .dout(grp_fu_158_p2)
);

fastvit_ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln202_fu_123_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_48 <= r_61_fu_129_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_48 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln207_reg_243 <= and_ln207_fu_184_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        in_r_reg_226 <= in_r_fu_139_p2;
        r_60_reg_212 <= ap_sig_allocacmp_r_60;
        trunc_ln204_reg_232 <= trunc_ln204_fu_145_p1;
        zext_ln202_1_reg_237[3 : 0] <= zext_ln202_1_fu_154_p1[3 : 0];
        zext_ln202_reg_221[3 : 0] <= zext_ln202_fu_135_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln205_reg_248 <= grp_fu_158_p2;
        zext_ln202_1_reg_237_pp0_iter2_reg[3 : 0] <= zext_ln202_1_reg_237[3 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln202_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_r_60 = 4'd0;
    end else begin
        ap_sig_allocacmp_r_60 = r_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        row_base_addr_ce0_local = 1'b1;
    end else begin
        row_base_addr_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        row_base_addr_we0_local = 1'b1;
    end else begin
        row_base_addr_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_in_bounds_ce0_local = 1'b1;
    end else begin
        row_in_bounds_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        row_in_bounds_we0_local = 1'b1;
    end else begin
        row_in_bounds_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_in_tile_ce0_local = 1'b1;
    end else begin
        row_in_tile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        row_in_tile_we0_local = 1'b1;
    end else begin
        row_in_tile_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln207_fu_184_p2 = (xor_ln207_fu_174_p2 & icmp_ln207_fu_180_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln202_fu_123_p2 = ((ap_sig_allocacmp_r_60 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln206_fu_162_p2 = (($signed(zext_ln202_reg_221) < $signed(in_tile_h)) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_180_p2 = (($signed(in_r_reg_226) < $signed(Hin)) ? 1'b1 : 1'b0);

assign in_r_fu_139_p2 = (empty_80 + zext_ln202_fu_135_p1);

assign r_61_fu_129_p2 = (ap_sig_allocacmp_r_60 + 4'd1);

assign row_base_addr_address0 = zext_ln202_1_reg_237_pp0_iter2_reg;

assign row_base_addr_ce0 = row_base_addr_ce0_local;

assign row_base_addr_d0 = mul_ln205_reg_248;

assign row_base_addr_we0 = row_base_addr_we0_local;

assign row_in_bounds_address0 = zext_ln202_1_reg_237;

assign row_in_bounds_ce0 = row_in_bounds_ce0_local;

assign row_in_bounds_d0 = and_ln207_reg_243;

assign row_in_bounds_we0 = row_in_bounds_we0_local;

assign row_in_tile_address0 = zext_ln202_1_fu_154_p1;

assign row_in_tile_ce0 = row_in_tile_ce0_local;

assign row_in_tile_d0 = icmp_ln206_fu_162_p2;

assign row_in_tile_we0 = row_in_tile_we0_local;

assign tmp_59_fu_167_p3 = in_r_reg_226[32'd31];

assign trunc_ln204_fu_145_p1 = in_r_fu_139_p2[11:0];

assign xor_ln207_fu_174_p2 = (tmp_59_fu_167_p3 ^ 1'd1);

assign zext_ln202_1_fu_154_p1 = r_60_reg_212;

assign zext_ln202_fu_135_p1 = ap_sig_allocacmp_r_60;

always @ (posedge ap_clk) begin
    zext_ln202_reg_221[31:4] <= 28'b0000000000000000000000000000;
    zext_ln202_1_reg_237[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln202_1_reg_237_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //fastvit_ip_dwconv_process_channel4_Pipeline_LOAD_DW_IN_ROWBASE
