// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fastvit_ip_dwconv_preload_channel3_Pipeline_PRELOAD_IN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY,
        m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY,
        m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID,
        m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP,
        m_axi_gmem0_0_BID,
        m_axi_gmem0_0_BUSER,
        hw_in_words,
        sext_ln85_1,
        p_ZL9ch_in_buf_15_address0,
        p_ZL9ch_in_buf_15_ce0,
        p_ZL9ch_in_buf_15_we0,
        p_ZL9ch_in_buf_15_d0,
        p_ZL9ch_in_buf_14_address0,
        p_ZL9ch_in_buf_14_ce0,
        p_ZL9ch_in_buf_14_we0,
        p_ZL9ch_in_buf_14_d0,
        p_ZL9ch_in_buf_13_address0,
        p_ZL9ch_in_buf_13_ce0,
        p_ZL9ch_in_buf_13_we0,
        p_ZL9ch_in_buf_13_d0,
        p_ZL9ch_in_buf_12_address0,
        p_ZL9ch_in_buf_12_ce0,
        p_ZL9ch_in_buf_12_we0,
        p_ZL9ch_in_buf_12_d0,
        p_ZL9ch_in_buf_11_address0,
        p_ZL9ch_in_buf_11_ce0,
        p_ZL9ch_in_buf_11_we0,
        p_ZL9ch_in_buf_11_d0,
        p_ZL9ch_in_buf_10_address0,
        p_ZL9ch_in_buf_10_ce0,
        p_ZL9ch_in_buf_10_we0,
        p_ZL9ch_in_buf_10_d0,
        p_ZL9ch_in_buf_9_address0,
        p_ZL9ch_in_buf_9_ce0,
        p_ZL9ch_in_buf_9_we0,
        p_ZL9ch_in_buf_9_d0,
        p_ZL9ch_in_buf_8_address0,
        p_ZL9ch_in_buf_8_ce0,
        p_ZL9ch_in_buf_8_we0,
        p_ZL9ch_in_buf_8_d0,
        p_ZL9ch_in_buf_7_address0,
        p_ZL9ch_in_buf_7_ce0,
        p_ZL9ch_in_buf_7_we0,
        p_ZL9ch_in_buf_7_d0,
        p_ZL9ch_in_buf_6_address0,
        p_ZL9ch_in_buf_6_ce0,
        p_ZL9ch_in_buf_6_we0,
        p_ZL9ch_in_buf_6_d0,
        p_ZL9ch_in_buf_5_address0,
        p_ZL9ch_in_buf_5_ce0,
        p_ZL9ch_in_buf_5_we0,
        p_ZL9ch_in_buf_5_d0,
        p_ZL9ch_in_buf_4_address0,
        p_ZL9ch_in_buf_4_ce0,
        p_ZL9ch_in_buf_4_we0,
        p_ZL9ch_in_buf_4_d0,
        p_ZL9ch_in_buf_3_address0,
        p_ZL9ch_in_buf_3_ce0,
        p_ZL9ch_in_buf_3_we0,
        p_ZL9ch_in_buf_3_d0,
        p_ZL9ch_in_buf_2_address0,
        p_ZL9ch_in_buf_2_ce0,
        p_ZL9ch_in_buf_2_we0,
        p_ZL9ch_in_buf_2_d0,
        p_ZL9ch_in_buf_1_address0,
        p_ZL9ch_in_buf_1_ce0,
        p_ZL9ch_in_buf_1_we0,
        p_ZL9ch_in_buf_1_d0,
        p_ZL9ch_in_buf_0_address0,
        p_ZL9ch_in_buf_0_ce0,
        p_ZL9ch_in_buf_0_we0,
        p_ZL9ch_in_buf_0_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_0_AWVALID;
input   m_axi_gmem0_0_AWREADY;
output  [63:0] m_axi_gmem0_0_AWADDR;
output  [0:0] m_axi_gmem0_0_AWID;
output  [31:0] m_axi_gmem0_0_AWLEN;
output  [2:0] m_axi_gmem0_0_AWSIZE;
output  [1:0] m_axi_gmem0_0_AWBURST;
output  [1:0] m_axi_gmem0_0_AWLOCK;
output  [3:0] m_axi_gmem0_0_AWCACHE;
output  [2:0] m_axi_gmem0_0_AWPROT;
output  [3:0] m_axi_gmem0_0_AWQOS;
output  [3:0] m_axi_gmem0_0_AWREGION;
output  [0:0] m_axi_gmem0_0_AWUSER;
output   m_axi_gmem0_0_WVALID;
input   m_axi_gmem0_0_WREADY;
output  [31:0] m_axi_gmem0_0_WDATA;
output  [3:0] m_axi_gmem0_0_WSTRB;
output   m_axi_gmem0_0_WLAST;
output  [0:0] m_axi_gmem0_0_WID;
output  [0:0] m_axi_gmem0_0_WUSER;
output   m_axi_gmem0_0_ARVALID;
input   m_axi_gmem0_0_ARREADY;
output  [63:0] m_axi_gmem0_0_ARADDR;
output  [0:0] m_axi_gmem0_0_ARID;
output  [31:0] m_axi_gmem0_0_ARLEN;
output  [2:0] m_axi_gmem0_0_ARSIZE;
output  [1:0] m_axi_gmem0_0_ARBURST;
output  [1:0] m_axi_gmem0_0_ARLOCK;
output  [3:0] m_axi_gmem0_0_ARCACHE;
output  [2:0] m_axi_gmem0_0_ARPROT;
output  [3:0] m_axi_gmem0_0_ARQOS;
output  [3:0] m_axi_gmem0_0_ARREGION;
output  [0:0] m_axi_gmem0_0_ARUSER;
input   m_axi_gmem0_0_RVALID;
output   m_axi_gmem0_0_RREADY;
input  [31:0] m_axi_gmem0_0_RDATA;
input   m_axi_gmem0_0_RLAST;
input  [0:0] m_axi_gmem0_0_RID;
input  [10:0] m_axi_gmem0_0_RFIFONUM;
input  [0:0] m_axi_gmem0_0_RUSER;
input  [1:0] m_axi_gmem0_0_RRESP;
input   m_axi_gmem0_0_BVALID;
output   m_axi_gmem0_0_BREADY;
input  [1:0] m_axi_gmem0_0_BRESP;
input  [0:0] m_axi_gmem0_0_BID;
input  [0:0] m_axi_gmem0_0_BUSER;
input  [28:0] hw_in_words;
input  [61:0] sext_ln85_1;
output  [7:0] p_ZL9ch_in_buf_15_address0;
output   p_ZL9ch_in_buf_15_ce0;
output   p_ZL9ch_in_buf_15_we0;
output  [3:0] p_ZL9ch_in_buf_15_d0;
output  [7:0] p_ZL9ch_in_buf_14_address0;
output   p_ZL9ch_in_buf_14_ce0;
output   p_ZL9ch_in_buf_14_we0;
output  [3:0] p_ZL9ch_in_buf_14_d0;
output  [7:0] p_ZL9ch_in_buf_13_address0;
output   p_ZL9ch_in_buf_13_ce0;
output   p_ZL9ch_in_buf_13_we0;
output  [3:0] p_ZL9ch_in_buf_13_d0;
output  [7:0] p_ZL9ch_in_buf_12_address0;
output   p_ZL9ch_in_buf_12_ce0;
output   p_ZL9ch_in_buf_12_we0;
output  [3:0] p_ZL9ch_in_buf_12_d0;
output  [7:0] p_ZL9ch_in_buf_11_address0;
output   p_ZL9ch_in_buf_11_ce0;
output   p_ZL9ch_in_buf_11_we0;
output  [3:0] p_ZL9ch_in_buf_11_d0;
output  [7:0] p_ZL9ch_in_buf_10_address0;
output   p_ZL9ch_in_buf_10_ce0;
output   p_ZL9ch_in_buf_10_we0;
output  [3:0] p_ZL9ch_in_buf_10_d0;
output  [7:0] p_ZL9ch_in_buf_9_address0;
output   p_ZL9ch_in_buf_9_ce0;
output   p_ZL9ch_in_buf_9_we0;
output  [3:0] p_ZL9ch_in_buf_9_d0;
output  [7:0] p_ZL9ch_in_buf_8_address0;
output   p_ZL9ch_in_buf_8_ce0;
output   p_ZL9ch_in_buf_8_we0;
output  [3:0] p_ZL9ch_in_buf_8_d0;
output  [7:0] p_ZL9ch_in_buf_7_address0;
output   p_ZL9ch_in_buf_7_ce0;
output   p_ZL9ch_in_buf_7_we0;
output  [3:0] p_ZL9ch_in_buf_7_d0;
output  [7:0] p_ZL9ch_in_buf_6_address0;
output   p_ZL9ch_in_buf_6_ce0;
output   p_ZL9ch_in_buf_6_we0;
output  [3:0] p_ZL9ch_in_buf_6_d0;
output  [7:0] p_ZL9ch_in_buf_5_address0;
output   p_ZL9ch_in_buf_5_ce0;
output   p_ZL9ch_in_buf_5_we0;
output  [3:0] p_ZL9ch_in_buf_5_d0;
output  [7:0] p_ZL9ch_in_buf_4_address0;
output   p_ZL9ch_in_buf_4_ce0;
output   p_ZL9ch_in_buf_4_we0;
output  [3:0] p_ZL9ch_in_buf_4_d0;
output  [7:0] p_ZL9ch_in_buf_3_address0;
output   p_ZL9ch_in_buf_3_ce0;
output   p_ZL9ch_in_buf_3_we0;
output  [3:0] p_ZL9ch_in_buf_3_d0;
output  [7:0] p_ZL9ch_in_buf_2_address0;
output   p_ZL9ch_in_buf_2_ce0;
output   p_ZL9ch_in_buf_2_we0;
output  [3:0] p_ZL9ch_in_buf_2_d0;
output  [7:0] p_ZL9ch_in_buf_1_address0;
output   p_ZL9ch_in_buf_1_ce0;
output   p_ZL9ch_in_buf_1_we0;
output  [3:0] p_ZL9ch_in_buf_1_d0;
output  [7:0] p_ZL9ch_in_buf_0_address0;
output   p_ZL9ch_in_buf_0_ce0;
output   p_ZL9ch_in_buf_0_we0;
output  [3:0] p_ZL9ch_in_buf_0_d0;

reg ap_idle;
reg m_axi_gmem0_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln85_fu_349_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln85_fu_361_p1;
reg   [0:0] trunc_ln85_reg_481;
reg   [0:0] trunc_ln85_reg_481_pp0_iter1_reg;
reg   [7:0] lshr_ln_reg_485;
reg   [7:0] lshr_ln_reg_485_pp0_iter1_reg;
wire   [3:0] trunc_ln88_fu_386_p1;
reg   [3:0] trunc_ln88_reg_490;
reg   [3:0] tmp_i_i_reg_496;
reg   [3:0] tmp_43_i_i_reg_502;
reg   [3:0] tmp_44_i_i_reg_508;
reg   [3:0] tmp_45_i_i_reg_514;
reg   [3:0] tmp_46_i_i_reg_520;
reg   [3:0] tmp_47_i_i_reg_526;
reg   [3:0] tmp_48_i_i_reg_532;
wire   [63:0] zext_ln88_fu_446_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [27:0] hw_fu_104;
wire   [27:0] add_ln85_fu_355_p2;
wire    ap_loop_init;
reg   [27:0] ap_sig_allocacmp_hw_2;
wire    ap_block_pp0_stage0;
reg    p_ZL9ch_in_buf_0_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    p_ZL9ch_in_buf_0_ce0_local;
reg    p_ZL9ch_in_buf_1_we0_local;
reg    p_ZL9ch_in_buf_1_ce0_local;
reg    p_ZL9ch_in_buf_2_we0_local;
reg    p_ZL9ch_in_buf_2_ce0_local;
reg    p_ZL9ch_in_buf_3_we0_local;
reg    p_ZL9ch_in_buf_3_ce0_local;
reg    p_ZL9ch_in_buf_4_we0_local;
reg    p_ZL9ch_in_buf_4_ce0_local;
reg    p_ZL9ch_in_buf_5_we0_local;
reg    p_ZL9ch_in_buf_5_ce0_local;
reg    p_ZL9ch_in_buf_6_we0_local;
reg    p_ZL9ch_in_buf_6_ce0_local;
reg    p_ZL9ch_in_buf_7_we0_local;
reg    p_ZL9ch_in_buf_7_ce0_local;
reg    p_ZL9ch_in_buf_8_we0_local;
reg    p_ZL9ch_in_buf_8_ce0_local;
reg    p_ZL9ch_in_buf_9_we0_local;
reg    p_ZL9ch_in_buf_9_ce0_local;
reg    p_ZL9ch_in_buf_10_we0_local;
reg    p_ZL9ch_in_buf_10_ce0_local;
reg    p_ZL9ch_in_buf_11_we0_local;
reg    p_ZL9ch_in_buf_11_ce0_local;
reg    p_ZL9ch_in_buf_12_we0_local;
reg    p_ZL9ch_in_buf_12_ce0_local;
reg    p_ZL9ch_in_buf_13_we0_local;
reg    p_ZL9ch_in_buf_13_ce0_local;
reg    p_ZL9ch_in_buf_14_we0_local;
reg    p_ZL9ch_in_buf_14_ce0_local;
reg    p_ZL9ch_in_buf_15_we0_local;
reg    p_ZL9ch_in_buf_15_ce0_local;
wire   [28:0] zext_ln85_fu_345_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 hw_fu_104 = 28'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

fastvit_ip_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln85_fu_349_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            hw_fu_104 <= add_ln85_fu_355_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hw_fu_104 <= 28'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        lshr_ln_reg_485 <= {{ap_sig_allocacmp_hw_2[8:1]}};
        lshr_ln_reg_485_pp0_iter1_reg <= lshr_ln_reg_485;
        trunc_ln85_reg_481 <= trunc_ln85_fu_361_p1;
        trunc_ln85_reg_481_pp0_iter1_reg <= trunc_ln85_reg_481;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_43_i_i_reg_502 <= {{m_axi_gmem0_0_RDATA[11:8]}};
        tmp_44_i_i_reg_508 <= {{m_axi_gmem0_0_RDATA[15:12]}};
        tmp_45_i_i_reg_514 <= {{m_axi_gmem0_0_RDATA[19:16]}};
        tmp_46_i_i_reg_520 <= {{m_axi_gmem0_0_RDATA[23:20]}};
        tmp_47_i_i_reg_526 <= {{m_axi_gmem0_0_RDATA[27:24]}};
        tmp_48_i_i_reg_532 <= {{m_axi_gmem0_0_RDATA[31:28]}};
        tmp_i_i_reg_496 <= {{m_axi_gmem0_0_RDATA[7:4]}};
        trunc_ln88_reg_490 <= trunc_ln88_fu_386_p1;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_349_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_hw_2 = 28'd0;
    end else begin
        ap_sig_allocacmp_hw_2 = hw_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_0_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_0_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_10_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_10_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_11_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_11_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_12_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_12_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_13_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_13_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_14_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_14_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_15_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_15_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_1_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_1_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_2_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_2_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_3_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_3_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_4_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_4_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_5_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_5_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_6_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_6_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_7_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd0))) begin
        p_ZL9ch_in_buf_7_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_8_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_8_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL9ch_in_buf_9_ce0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln85_reg_481_pp0_iter1_reg == 1'd1))) begin
        p_ZL9ch_in_buf_9_we0_local = 1'b1;
    end else begin
        p_ZL9ch_in_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_355_p2 = (ap_sig_allocacmp_hw_2 + 28'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln85_fu_349_p2 = (($signed(zext_ln85_fu_345_p1) < $signed(hw_in_words)) ? 1'b1 : 1'b0);

assign m_axi_gmem0_0_ARADDR = 64'd0;

assign m_axi_gmem0_0_ARBURST = 2'd0;

assign m_axi_gmem0_0_ARCACHE = 4'd0;

assign m_axi_gmem0_0_ARID = 1'd0;

assign m_axi_gmem0_0_ARLEN = 32'd0;

assign m_axi_gmem0_0_ARLOCK = 2'd0;

assign m_axi_gmem0_0_ARPROT = 3'd0;

assign m_axi_gmem0_0_ARQOS = 4'd0;

assign m_axi_gmem0_0_ARREGION = 4'd0;

assign m_axi_gmem0_0_ARSIZE = 3'd0;

assign m_axi_gmem0_0_ARUSER = 1'd0;

assign m_axi_gmem0_0_ARVALID = 1'b0;

assign m_axi_gmem0_0_AWADDR = 64'd0;

assign m_axi_gmem0_0_AWBURST = 2'd0;

assign m_axi_gmem0_0_AWCACHE = 4'd0;

assign m_axi_gmem0_0_AWID = 1'd0;

assign m_axi_gmem0_0_AWLEN = 32'd0;

assign m_axi_gmem0_0_AWLOCK = 2'd0;

assign m_axi_gmem0_0_AWPROT = 3'd0;

assign m_axi_gmem0_0_AWQOS = 4'd0;

assign m_axi_gmem0_0_AWREGION = 4'd0;

assign m_axi_gmem0_0_AWSIZE = 3'd0;

assign m_axi_gmem0_0_AWUSER = 1'd0;

assign m_axi_gmem0_0_AWVALID = 1'b0;

assign m_axi_gmem0_0_BREADY = 1'b0;

assign m_axi_gmem0_0_WDATA = 32'd0;

assign m_axi_gmem0_0_WID = 1'd0;

assign m_axi_gmem0_0_WLAST = 1'b0;

assign m_axi_gmem0_0_WSTRB = 4'd0;

assign m_axi_gmem0_0_WUSER = 1'd0;

assign m_axi_gmem0_0_WVALID = 1'b0;

assign p_ZL9ch_in_buf_0_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_0_ce0 = p_ZL9ch_in_buf_0_ce0_local;

assign p_ZL9ch_in_buf_0_d0 = trunc_ln88_reg_490;

assign p_ZL9ch_in_buf_0_we0 = p_ZL9ch_in_buf_0_we0_local;

assign p_ZL9ch_in_buf_10_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_10_ce0 = p_ZL9ch_in_buf_10_ce0_local;

assign p_ZL9ch_in_buf_10_d0 = tmp_43_i_i_reg_502;

assign p_ZL9ch_in_buf_10_we0 = p_ZL9ch_in_buf_10_we0_local;

assign p_ZL9ch_in_buf_11_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_11_ce0 = p_ZL9ch_in_buf_11_ce0_local;

assign p_ZL9ch_in_buf_11_d0 = tmp_44_i_i_reg_508;

assign p_ZL9ch_in_buf_11_we0 = p_ZL9ch_in_buf_11_we0_local;

assign p_ZL9ch_in_buf_12_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_12_ce0 = p_ZL9ch_in_buf_12_ce0_local;

assign p_ZL9ch_in_buf_12_d0 = tmp_45_i_i_reg_514;

assign p_ZL9ch_in_buf_12_we0 = p_ZL9ch_in_buf_12_we0_local;

assign p_ZL9ch_in_buf_13_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_13_ce0 = p_ZL9ch_in_buf_13_ce0_local;

assign p_ZL9ch_in_buf_13_d0 = tmp_46_i_i_reg_520;

assign p_ZL9ch_in_buf_13_we0 = p_ZL9ch_in_buf_13_we0_local;

assign p_ZL9ch_in_buf_14_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_14_ce0 = p_ZL9ch_in_buf_14_ce0_local;

assign p_ZL9ch_in_buf_14_d0 = tmp_47_i_i_reg_526;

assign p_ZL9ch_in_buf_14_we0 = p_ZL9ch_in_buf_14_we0_local;

assign p_ZL9ch_in_buf_15_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_15_ce0 = p_ZL9ch_in_buf_15_ce0_local;

assign p_ZL9ch_in_buf_15_d0 = tmp_48_i_i_reg_532;

assign p_ZL9ch_in_buf_15_we0 = p_ZL9ch_in_buf_15_we0_local;

assign p_ZL9ch_in_buf_1_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_1_ce0 = p_ZL9ch_in_buf_1_ce0_local;

assign p_ZL9ch_in_buf_1_d0 = tmp_i_i_reg_496;

assign p_ZL9ch_in_buf_1_we0 = p_ZL9ch_in_buf_1_we0_local;

assign p_ZL9ch_in_buf_2_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_2_ce0 = p_ZL9ch_in_buf_2_ce0_local;

assign p_ZL9ch_in_buf_2_d0 = tmp_43_i_i_reg_502;

assign p_ZL9ch_in_buf_2_we0 = p_ZL9ch_in_buf_2_we0_local;

assign p_ZL9ch_in_buf_3_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_3_ce0 = p_ZL9ch_in_buf_3_ce0_local;

assign p_ZL9ch_in_buf_3_d0 = tmp_44_i_i_reg_508;

assign p_ZL9ch_in_buf_3_we0 = p_ZL9ch_in_buf_3_we0_local;

assign p_ZL9ch_in_buf_4_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_4_ce0 = p_ZL9ch_in_buf_4_ce0_local;

assign p_ZL9ch_in_buf_4_d0 = tmp_45_i_i_reg_514;

assign p_ZL9ch_in_buf_4_we0 = p_ZL9ch_in_buf_4_we0_local;

assign p_ZL9ch_in_buf_5_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_5_ce0 = p_ZL9ch_in_buf_5_ce0_local;

assign p_ZL9ch_in_buf_5_d0 = tmp_46_i_i_reg_520;

assign p_ZL9ch_in_buf_5_we0 = p_ZL9ch_in_buf_5_we0_local;

assign p_ZL9ch_in_buf_6_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_6_ce0 = p_ZL9ch_in_buf_6_ce0_local;

assign p_ZL9ch_in_buf_6_d0 = tmp_47_i_i_reg_526;

assign p_ZL9ch_in_buf_6_we0 = p_ZL9ch_in_buf_6_we0_local;

assign p_ZL9ch_in_buf_7_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_7_ce0 = p_ZL9ch_in_buf_7_ce0_local;

assign p_ZL9ch_in_buf_7_d0 = tmp_48_i_i_reg_532;

assign p_ZL9ch_in_buf_7_we0 = p_ZL9ch_in_buf_7_we0_local;

assign p_ZL9ch_in_buf_8_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_8_ce0 = p_ZL9ch_in_buf_8_ce0_local;

assign p_ZL9ch_in_buf_8_d0 = trunc_ln88_reg_490;

assign p_ZL9ch_in_buf_8_we0 = p_ZL9ch_in_buf_8_we0_local;

assign p_ZL9ch_in_buf_9_address0 = zext_ln88_fu_446_p1;

assign p_ZL9ch_in_buf_9_ce0 = p_ZL9ch_in_buf_9_ce0_local;

assign p_ZL9ch_in_buf_9_d0 = tmp_i_i_reg_496;

assign p_ZL9ch_in_buf_9_we0 = p_ZL9ch_in_buf_9_we0_local;

assign trunc_ln85_fu_361_p1 = ap_sig_allocacmp_hw_2[0:0];

assign trunc_ln88_fu_386_p1 = m_axi_gmem0_0_RDATA[3:0];

assign zext_ln85_fu_345_p1 = ap_sig_allocacmp_hw_2;

assign zext_ln88_fu_446_p1 = lshr_ln_reg_485_pp0_iter1_reg;

endmodule //fastvit_ip_dwconv_preload_channel3_Pipeline_PRELOAD_IN
