/*
 * layer_descriptor_256.h -- auto-generated by tools/gen_layer_descriptor_header.py
 * FROM tools/layer_descriptor_256.json (Phase A step 2a, 0-diff self-checked
 * against layer_dag_ground_truth.json). DO NOT hand-edit -- regenerate.
 * Shape/stride/pad/group/fpg only; DAG consumer info is in the .json, not here
 * (this round's driver does not implement the bug-4 residual fix, see script
 * docstring -- defect 5, Add write-back failure, blocks it).
 */

#ifndef __LAYER_DESCRIPTOR_256_H__
#define __LAYER_DESCRIPTOR_256_H__

typedef struct {
    int cin, cout;
    int h_in, w_in;
    int k, stride, pad;
    int group, fpg;
} FvLayerDesc256;

#define FV_NUM_LAYERS_256  52

static const FvLayerDesc256 FV_DESC_256[FV_NUM_LAYERS_256] = {
    /* layer_0000_conv            node   0 /stem/stem.0/reparam_conv/Conv */
    {    3,   48, 256, 256, 3, 2, 1,    1, 1 },
    /* layer_0001_dwconv          node   6 /stem/stem.1/reparam_conv/Conv */
    {   48,   48, 128, 128, 3, 2, 1,   48, 1 },
    /* layer_0002_pwconv          node  12 /stem/stem.2/reparam_conv/Conv */
    {   48,   48,  64,  64, 1, 1, 0,    1, 1 },
    /* layer_0003_dwconv          node  18 /stages.0/blocks/blocks.0/token_mixer/reparam_conv/Conv */
    {   48,   48,  64,  64, 3, 1, 1,   48, 1 },
    /* layer_0004_dwconv          node  19 /stages.0/blocks/blocks.0/mlp/conv/conv/Conv */
    {   48,   48,  64,  64, 7, 1, 3,   48, 1 },
    /* layer_0005_pwconv          node  20 /stages.0/blocks/blocks.0/mlp/fc1/Conv */
    {   48,  144,  64,  64, 1, 1, 0,    1, 1 },
    /* layer_0006_pwconv          node  26 /stages.0/blocks/blocks.0/mlp/fc2/Conv */
    {  144,   48,  64,  64, 1, 1, 0,    1, 1 },
    /* layer_0007_dwconv          node  29 /stages.0/blocks/blocks.1/token_mixer/reparam_conv/Conv */
    {   48,   48,  64,  64, 3, 1, 1,   48, 1 },
    /* layer_0008_dwconv          node  30 /stages.0/blocks/blocks.1/mlp/conv/conv/Conv */
    {   48,   48,  64,  64, 7, 1, 3,   48, 1 },
    /* layer_0009_pwconv          node  31 /stages.0/blocks/blocks.1/mlp/fc1/Conv */
    {   48,  144,  64,  64, 1, 1, 0,    1, 1 },
    /* layer_0010_pwconv          node  37 /stages.0/blocks/blocks.1/mlp/fc2/Conv */
    {  144,   48,  64,  64, 1, 1, 0,    1, 1 },
    /* layer_0011_dwconv          node  40 /stages.1/downsample/proj/proj.0/reparam_conv/Conv */
    {   48,   96,  64,  64, 7, 2, 3,   48, 2 },
    /* layer_0012_pwconv          node  41 /stages.1/downsample/proj/proj.1/reparam_conv/Conv */
    {   96,   96,  32,  32, 1, 1, 0,    1, 1 },
    /* layer_0013_dwconv          node  47 /stages.1/blocks/blocks.0/token_mixer/reparam_conv/Conv */
    {   96,   96,  32,  32, 3, 1, 1,   96, 1 },
    /* layer_0014_dwconv          node  48 /stages.1/blocks/blocks.0/mlp/conv/conv/Conv */
    {   96,   96,  32,  32, 7, 1, 3,   96, 1 },
    /* layer_0015_pwconv          node  49 /stages.1/blocks/blocks.0/mlp/fc1/Conv */
    {   96,  240,  32,  32, 1, 1, 0,    1, 1 },
    /* layer_0016_pwconv          node  55 /stages.1/blocks/blocks.0/mlp/fc2/Conv */
    {  240,   96,  32,  32, 1, 1, 0,    1, 1 },
    /* layer_0017_dwconv          node  58 /stages.1/blocks/blocks.1/token_mixer/reparam_conv/Conv */
    {   96,   96,  32,  32, 3, 1, 1,   96, 1 },
    /* layer_0018_dwconv          node  59 /stages.1/blocks/blocks.1/mlp/conv/conv/Conv */
    {   96,   96,  32,  32, 7, 1, 3,   96, 1 },
    /* layer_0019_pwconv          node  60 /stages.1/blocks/blocks.1/mlp/fc1/Conv */
    {   96,  288,  32,  32, 1, 1, 0,    1, 1 },
    /* layer_0020_pwconv          node  66 /stages.1/blocks/blocks.1/mlp/fc2/Conv */
    {  288,   96,  32,  32, 1, 1, 0,    1, 1 },
    /* layer_0021_dwconv          node  69 /stages.2/downsample/proj/proj.0/reparam_conv/Conv */
    {   96,  192,  32,  32, 7, 2, 3,   96, 2 },
    /* layer_0022_pwconv          node  70 /stages.2/downsample/proj/proj.1/reparam_conv/Conv */
    {  192,  192,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0023_dwconv          node  76 /stages.2/blocks/blocks.0/token_mixer/reparam_conv/Conv */
    {  192,  192,  16,  16, 3, 1, 1,  192, 1 },
    /* layer_0024_dwconv          node  77 /stages.2/blocks/blocks.0/mlp/conv/conv/Conv */
    {  192,  192,  16,  16, 7, 1, 3,  192, 1 },
    /* layer_0025_pwconv          node  78 /stages.2/blocks/blocks.0/mlp/fc1/Conv */
    {  192,  576,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0026_pwconv          node  84 /stages.2/blocks/blocks.0/mlp/fc2/Conv */
    {  576,  192,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0027_dwconv          node  87 /stages.2/blocks/blocks.1/token_mixer/reparam_conv/Conv */
    {  192,  192,  16,  16, 3, 1, 1,  192, 1 },
    /* layer_0028_dwconv          node  88 /stages.2/blocks/blocks.1/mlp/conv/conv/Conv */
    {  192,  192,  16,  16, 7, 1, 3,  192, 1 },
    /* layer_0029_pwconv          node  89 /stages.2/blocks/blocks.1/mlp/fc1/Conv */
    {  192,  480,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0030_pwconv          node  95 /stages.2/blocks/blocks.1/mlp/fc2/Conv */
    {  480,  192,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0031_dwconv          node  98 /stages.2/blocks/blocks.2/token_mixer/reparam_conv/Conv */
    {  192,  192,  16,  16, 3, 1, 1,  192, 1 },
    /* layer_0032_dwconv          node  99 /stages.2/blocks/blocks.2/mlp/conv/conv/Conv */
    {  192,  192,  16,  16, 7, 1, 3,  192, 1 },
    /* layer_0033_pwconv          node 100 /stages.2/blocks/blocks.2/mlp/fc1/Conv */
    {  192,  576,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0034_pwconv          node 106 /stages.2/blocks/blocks.2/mlp/fc2/Conv */
    {  576,  192,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0035_dwconv          node 109 /stages.2/blocks/blocks.3/token_mixer/reparam_conv/Conv */
    {  192,  192,  16,  16, 3, 1, 1,  192, 1 },
    /* layer_0036_dwconv          node 110 /stages.2/blocks/blocks.3/mlp/conv/conv/Conv */
    {  192,  192,  16,  16, 7, 1, 3,  192, 1 },
    /* layer_0037_pwconv          node 111 /stages.2/blocks/blocks.3/mlp/fc1/Conv */
    {  192,  576,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0038_pwconv          node 117 /stages.2/blocks/blocks.3/mlp/fc2/Conv */
    {  576,  192,  16,  16, 1, 1, 0,    1, 1 },
    /* layer_0039_dwconv          node 120 /stages.3/downsample/proj/proj.0/reparam_conv/Conv */
    {  192,  384,  16,  16, 7, 2, 3,  192, 2 },
    /* layer_0040_pwconv          node 121 /stages.3/downsample/proj/proj.1/reparam_conv/Conv */
    {  384,  384,   8,   8, 1, 1, 0,    1, 1 },
    /* layer_0041_dwconv          node 127 /stages.3/blocks/blocks.0/token_mixer/reparam_conv/Conv */
    {  384,  384,   8,   8, 3, 1, 1,  384, 1 },
    /* layer_0042_dwconv          node 128 /stages.3/blocks/blocks.0/mlp/conv/conv/Conv */
    {  384,  384,   8,   8, 7, 1, 3,  384, 1 },
    /* layer_0043_pwconv          node 129 /stages.3/blocks/blocks.0/mlp/fc1/Conv */
    {  384, 1152,   8,   8, 1, 1, 0,    1, 1 },
    /* layer_0044_pwconv          node 135 /stages.3/blocks/blocks.0/mlp/fc2/Conv */
    { 1152,  384,   8,   8, 1, 1, 0,    1, 1 },
    /* layer_0045_dwconv          node 138 /stages.3/blocks/blocks.1/token_mixer/reparam_conv/Conv */
    {  384,  384,   8,   8, 3, 1, 1,  384, 1 },
    /* layer_0046_dwconv          node 139 /stages.3/blocks/blocks.1/mlp/conv/conv/Conv */
    {  384,  384,   8,   8, 7, 1, 3,  384, 1 },
    /* layer_0047_pwconv          node 140 /stages.3/blocks/blocks.1/mlp/fc1/Conv */
    {  384,  960,   8,   8, 1, 1, 0,    1, 1 },
    /* layer_0048_pwconv          node 146 /stages.3/blocks/blocks.1/mlp/fc2/Conv */
    {  960,  384,   8,   8, 1, 1, 0,    1, 1 },
    /* layer_0049_dwconv          node 149 /final_conv/reparam_conv/Conv */
    {  384,  768,   8,   8, 3, 1, 1,  384, 2 },
    /* layer_0050_pwconv          node 151 /final_conv/se/fc1/Conv */
    {  768,   48,   1,   1, 1, 1, 0,    1, 1 },
    /* layer_0051_pwconv          node 153 /final_conv/se/fc2/Conv */
    {   48,  768,   1,   1, 1, 1, 0,    1, 1 },
};

#endif /* __LAYER_DESCRIPTOR_256_H__ */
