"""
gen_layer_topology.py -- Phase 0.8 step 2

Generates a per-layer topology table (H_in/W_in/K/stride/pad/fpg/group) for
all 52 Conv layers, straight from the real ONNX graph via shape inference --
replacing the hand-typed stride/H/W constants in fastvit_infer.c that caused
the 3 topology bugs found in Phase 0.7 step 10 (see ZHR-8/ZHR-63 2026-08-15):

  1. Stem's 2nd conv (layer_0001) hardcoded stride=(1,1), real stride=(2,2)
  2. FinalDW (layer_0049) hardcoded stride=(2,2), real stride=(1,1)
  3. Stage1 block0's token_mixer (layer_0003) never dispatched at all

Channel counts (Cin/Cout) are NOT taken from the raw ONNX weight shape --
3 layers (0015/0016, 0029/0030, 0047/0048) are deliberately pruned narrower
than the ONNX graph by tools/export_weights_pruned.py, and that pruned
channel count is the deployed truth. Cin/Cout here come from
weights_t8_pruned/quant_config.json (the same file that already drives
weights_layout.h), cross-referenced to the ONNX graph via each entry's
node_idx. Spatial shape (H_in/W_in) and the stride/pad/kernel/group
attributes -- the fields actually responsible for the 3 bugs -- come from
the ONNX graph itself via onnx.shape_inference, since pruning never touches
spatial size or stride.

Usage:
  python gen_layer_topology.py [--model <onnx>] [--quant-config <json>]
                                [--out <header path>]
"""
import onnx
import onnx.shape_inference
import json
import argparse
import os


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--model", default=r"E:\codes\microzed\fastvit_t8_processed_128x128.onnx")
    p.add_argument("--quant-config",
                   default=r"E:\codes\microzed\fastvit_hls\weights_t8_pruned\quant_config.json")
    p.add_argument("--out",
                   default=r"E:\codes\microzed\fastvit_hls\petalinux\software\fastvit_app\include\layer_topology.h")
    return p.parse_args()


def node_attrs(n):
    return {a.name: (list(a.ints) if a.ints else a.i) for a in n.attribute}


def main():
    args = parse_args()

    model = onnx.load(args.model)
    inferred = onnx.shape_inference.infer_shapes(model)
    graph = inferred.graph

    shape_map = {}
    for vi in list(graph.value_info) + list(graph.input) + list(graph.output):
        dims = vi.type.tensor_type.shape.dim
        shape = [d.dim_value for d in dims]
        shape_map[vi.name] = shape

    with open(args.quant_config) as f:
        qcfg = json.load(f)

    # layer_XXXX_optype -> entry, sorted by the numeric layer index in the key
    layers = sorted(qcfg.items(), key=lambda kv: int(kv[0].split("_")[1]))
    assert len(layers) == 52, f"expected 52 layers in quant_config, found {len(layers)}"

    rows = []
    for tag, entry in layers:
        node_idx = entry["node_idx"]
        node = graph.node[node_idx]
        a = node_attrs(node)

        kernel = a.get("kernel_shape", [1, 1])
        stride = a.get("strides", [1, 1])
        pad = a.get("pads", [0, 0, 0, 0])
        group = a.get("group", 1)

        in_name = node.input[0]
        assert in_name in shape_map, f"{tag}: no shape info for input tensor {in_name!r}"
        in_shape = shape_map[in_name]
        assert len(in_shape) == 4, f"{tag}: expected NCHW input shape, got {in_shape}"
        h_in, w_in = in_shape[2], in_shape[3]

        cin = entry["Cin"]
        cout = entry["Cout"]
        op_type = entry["op_type"]

        # fpg (grouped-expand factor) only applies to depthwise convs where
        # Cout is a multiple of Cin > 1x (Transition layers, FinalDW); plain
        # depthwise (Stem dw, RepMixer dw3/dw7) has fpg=1.
        if op_type == "dwconv":
            assert cout % cin == 0, f"{tag}: dwconv Cout={cout} not a multiple of Cin={cin}"
            fpg = cout // cin
        else:
            fpg = 1

        rows.append({
            "tag": tag,
            "node_idx": node_idx,
            "node_name": node.name,
            "op_type": op_type,
            "cin": cin, "cout": cout,
            "h_in": h_in, "w_in": w_in,
            "k": kernel[0], "stride": stride[0], "pad": pad[0],
            "group": group, "fpg": fpg,
        })
        assert kernel[0] == kernel[1], f"{tag}: non-square kernel {kernel}"
        assert stride[0] == stride[1], f"{tag}: non-square stride {stride}"
        assert pad[0] == pad[1] == pad[2] == pad[3], f"{tag}: asymmetric pad {pad}"

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * layer_topology.h -- auto-generated by tools/gen_layer_topology.py\n")
        f.write(" * Phase 0.8: per-layer H_in/W_in/K/stride/pad/group/fpg, sourced from\n")
        f.write(" * the real ONNX graph (shape inference) + weights_t8_pruned/quant_config.json\n")
        f.write(" * (channel counts, post-pruning truth). DO NOT hand-edit -- regenerate.\n")
        f.write(f" * model: {os.path.basename(args.model)}\n")
        f.write(" */\n\n")
        f.write("#ifndef __LAYER_TOPOLOGY_H__\n#define __LAYER_TOPOLOGY_H__\n\n")
        f.write("typedef struct {\n")
        f.write("    int cin, cout;\n")
        f.write("    int h_in, w_in;\n")
        f.write("    int k, stride, pad;\n")
        f.write("    int group, fpg;\n")
        f.write("} FvLayerTopo;\n\n")
        f.write(f"#define FV_NUM_LAYERS_TOPO  {len(rows)}\n\n")
        f.write("static const FvLayerTopo FV_TOPO[FV_NUM_LAYERS_TOPO] = {\n")
        for r in rows:
            f.write(
                f"    /* {r['tag']:26s} node {r['node_idx']:3d} {r['node_name']} */\n"
                f"    {{ {r['cin']:4d}, {r['cout']:4d}, "
                f"{r['h_in']:3d}, {r['w_in']:3d}, "
                f"{r['k']}, {r['stride']}, {r['pad']}, "
                f"{r['group']:4d}, {r['fpg']} }},\n"
            )
        f.write("};\n\n")
        f.write("#endif /* __LAYER_TOPOLOGY_H__ */\n")

    print(f"wrote {args.out} ({len(rows)} layers)")
    print("\n=== sanity spot-check (the 3 previously-known bugs) ===")
    for i in (1, 3, 49):
        r = rows[i]
        print(f"  layer_{i:04d} {r['op_type']:8s} cin={r['cin']:4d} cout={r['cout']:4d} "
              f"h_in={r['h_in']:3d} w_in={r['w_in']:3d} k={r['k']} stride={r['stride']} "
              f"pad={r['pad']} fpg={r['fpg']}")


if __name__ == "__main__":
    main()
