"""
gen_layer_descriptor_header.py -- Phase A checkpoint (2026-08-15).

Converts tools/layer_descriptor_256.json (the step-2a structural descriptor,
generated straight from the real 256x256 ONNX graph) into a C header, so the
board test can dispatch from the SAME artifact that was 0-diff self-checked
against the DAG ground truth -- not a re-derivation, not the older Phase 0.8
layer_topology.h. This is exactly the "generator output -> driver behavior"
link that has never been tested end-to-end (verify_layer_dag.py only proves
the JSON is internally consistent with the ONNX graph; it says nothing yet
about what actually happens once that JSON drives real hardware).

Only shape/stride/pad/group/fpg/weight-file fields are emitted here -- the
DAG `consumers` field is deliberately NOT translated into dispatch logic by
this script. The residual-add wiring fix implied by bug 4's consumer list
(token_mixer's raw output, not DW7's, feeding the Add) needs a 4th buffer
whose Add usage is the exact pattern already shown to silently fail on this
hardware (ZHR-8 2026-08-15, defect 5, unresolved). This round's driver
therefore deliberately keeps the OLD (wrong) residual operand -- DW7's
output instead of token_mixer's raw output -- using only the three
addresses (ping/pong/temp) already proven safe as Add operands, so this
checkpoint measures "structural/shape fixes only" without also gambling on
the still-broken Add path. This is a disclosed, temporary deviation from
the descriptor's literal DAG spec, not a silent regression -- 2b's roadmap
still calls for it once defect 5 has an actual fix.

用法:
  python gen_layer_descriptor_header.py [--descriptor <json>] [--out <header>]
"""
import json
import argparse
import os


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--descriptor",
                   default=r"E:\codes\microzed\fastvit_hls\tools\layer_descriptor_256.json")
    p.add_argument("--out",
                   default=r"E:\codes\microzed\fastvit_hls\petalinux\software\fastvit_app\include\layer_descriptor_256.h")
    return p.parse_args()


def main():
    args = parse_args()
    with open(args.descriptor) as f:
        layers = json.load(f)
    assert len(layers) == 52

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("/*\n")
        f.write(" * layer_descriptor_256.h -- auto-generated by tools/gen_layer_descriptor_header.py\n")
        f.write(" * FROM tools/layer_descriptor_256.json (Phase A step 2a, 0-diff self-checked\n")
        f.write(" * against layer_dag_ground_truth.json). DO NOT hand-edit -- regenerate.\n")
        f.write(" * Shape/stride/pad/group/fpg only; DAG consumer info is in the .json, not here\n")
        f.write(" * (this round's driver does not implement the bug-4 residual fix, see script\n")
        f.write(" * docstring -- defect 5, Add write-back failure, blocks it).\n")
        f.write(" */\n\n")
        f.write("#ifndef __LAYER_DESCRIPTOR_256_H__\n#define __LAYER_DESCRIPTOR_256_H__\n\n")
        f.write("typedef struct {\n")
        f.write("    int cin, cout;\n")
        f.write("    int h_in, w_in;\n")
        f.write("    int k, stride, pad;\n")
        f.write("    int group, fpg;\n")
        f.write("} FvLayerDesc256;\n\n")
        f.write(f"#define FV_NUM_LAYERS_256  {len(layers)}\n\n")
        f.write("static const FvLayerDesc256 FV_DESC_256[FV_NUM_LAYERS_256] = {\n")
        for l in layers:
            f.write(
                f"    /* {l['tag']:26s} node {l['node_idx']:3d} {l['node_name']} */\n"
                f"    {{ {l['cin']:4d}, {l['cout']:4d}, "
                f"{l['h_in']:3d}, {l['w_in']:3d}, "
                f"{l['k']}, {l['stride']}, {l['pad']}, "
                f"{l['group']:4d}, {l['fpg']} }},\n"
            )
        f.write("};\n\n")
        f.write("#endif /* __LAYER_DESCRIPTOR_256_H__ */\n")

    print(f"wrote {args.out} ({len(layers)} layers)")
    for i in (0, 1, 3, 49):
        l = layers[i]
        print(f"  layer_{i:04d} {l['op_type']:8s} cin={l['cin']:4d} cout={l['cout']:4d} "
              f"h_in={l['h_in']:4d} w_in={l['w_in']:4d} k={l['k']} stride={l['stride']} fpg={l['fpg']}")


if __name__ == "__main__":
    main()
