"""
gen_weights_layout.py
从 quant_config.json 生成 weights_layout.h:
  - 每层权重/偏置在 DDR 中的字节偏移量 (从 FV_DDR_BASE 起)
  - out_shift 值
  - 权重/偏置文件名列表 (供 main.c 按序加载)

用法:
  python gen_weights_layout.py \
    --cfg weights_t8/quant_config.json \
    --wdir weights_t8/ \
    --out arm_driver/weights_layout.h
"""
import json, os, argparse

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--cfg",  default=r"E:\codes\microzed\fastvit_hls\weights_t8\quant_config.json")
    p.add_argument("--wdir", default=r"E:\codes\microzed\fastvit_hls\weights_t8")
    p.add_argument("--out",  default=r"E:\codes\microzed\fastvit_hls\arm_driver\weights_layout.h")
    return p.parse_args()

def main():
    args = parse_args()
    with open(args.cfg) as f:
        cfg = json.load(f)

    layers = list(cfg.items())
    N = len(layers)
    print(f"[gen_weights_layout] {N} layers")

    # 按顺序布局: weight0, bias0, weight1, bias1, ...
    offsets   = []   # (w_off, b_off) per layer
    w_sizes   = []
    b_sizes   = []
    w_files   = []
    b_files   = []
    out_shifts= []
    total = 0

    for tag, meta in layers:
        op   = meta["op_type"]
        cout = meta["Cout"]
        cin  = meta["Cin"]
        k    = meta["kernel"]

        wf = meta["weight_file"]
        bf = meta["bias_file"]

        wp = os.path.join(args.wdir, wf) if wf else None
        bp = os.path.join(args.wdir, bf) if bf else None

        wsz = os.path.getsize(wp) if wp and os.path.exists(wp) else 0
        bsz = os.path.getsize(bp) if bp and os.path.exists(bp) else 0

        # Align to 4 bytes
        wsz_a = (wsz + 3) & ~3
        bsz_a = (bsz + 3) & ~3

        w_off = total
        b_off = total + wsz_a

        offsets.append((w_off, b_off))
        w_sizes.append(wsz)
        b_sizes.append(bsz)
        w_files.append(wf if wf else "")
        b_files.append(bf if bf else "")
        out_shifts.append(meta["out_shift"])

        total += wsz_a + bsz_a
        print(f"  [{len(offsets)-1:2d}] {op:8s} w_off={w_off:#010x} ({wsz}B) b_off={b_off:#010x} ({bsz}B)")

    total_kb = total / 1024
    print(f"Total DDR weight footprint: {total_kb:.1f} KB")

    # Write header
    with open(args.out, "w") as f:
        f.write("/*\n")
        f.write(" * weights_layout.h  —  auto-generated by gen_weights_layout.py\n")
        f.write(f" * {N} layers, total {total_kb:.1f} KB from FV_DDR_BASE\n")
        f.write(" */\n\n")
        f.write("#ifndef __WEIGHTS_LAYOUT_H__\n")
        f.write("#define __WEIGHTS_LAYOUT_H__\n\n")
        f.write("#include <stdint.h>\n")
        f.write('#include "fastvit_infer.h"\n\n')

        f.write(f"#define FV_NUM_LAYERS  {N}\n")
        f.write(f"#define FV_WEIGHT_TOTAL_BYTES  {total}UL  /* {total_kb:.1f} KB */\n\n")

        # File name list (for SD card loading)
        f.write("/* Weight/bias file names in order */\n")
        f.write(f"static const char *const FV_WEIGHT_FILES[{N}] = {{\n")
        for wf in w_files:
            f.write(f'    "{wf}",\n')
        f.write("};\n\n")

        f.write(f"static const char *const FV_BIAS_FILES[{N}] = {{\n")
        for bf in b_files:
            f.write(f'    "{bf if bf else ""}",\n')
        f.write("};\n\n")

        f.write(f"static const uint32_t FV_WEIGHT_SIZES[{N}] = {{\n    ")
        f.write(", ".join(str(s) for s in w_sizes))
        f.write("\n};\n\n")

        f.write(f"static const uint32_t FV_BIAS_SIZES[{N}] = {{\n    ")
        f.write(", ".join(str(s) for s in b_sizes))
        f.write("\n};\n\n")

        # offsets
        f.write(f"static const uint32_t FV_W_OFFSETS[{N}] = {{\n    ")
        f.write(", ".join(f"{o[0]}U" for o in offsets))
        f.write("\n};\n\n")

        f.write(f"static const uint32_t FV_B_OFFSETS[{N}] = {{\n    ")
        f.write(", ".join(f"{o[1]}U" for o in offsets))
        f.write("\n};\n\n")

        f.write(f"static const int32_t FV_OUT_SHIFTS[{N}] = {{\n    ")
        f.write(", ".join(str(s) for s in out_shifts))
        f.write("\n};\n\n")

        # Build LayerWeight array from DDR base
        f.write("/* Build LayerWeight array once weights are loaded into DDR */\n")
        f.write("static inline void fv_build_layer_weights(\n")
        f.write("    LayerWeight *lw, uint32_t ddr_base)\n")
        f.write("{\n")
        f.write(f"    for (int i = 0; i < {N}; i++) {{\n")
        f.write("        lw[i].w_addr    = ddr_base + FV_W_OFFSETS[i];\n")
        f.write("        lw[i].b_addr    = (FV_BIAS_SIZES[i] > 0) ? (ddr_base + FV_B_OFFSETS[i]) : 0;\n")
        f.write("        lw[i].w_size    = FV_WEIGHT_SIZES[i];\n")
        f.write("        lw[i].b_size    = FV_BIAS_SIZES[i];\n")
        f.write("        lw[i].out_shift = FV_OUT_SHIFTS[i];\n")
        f.write("    }\n")
        f.write("}\n\n")

        f.write("#endif /* __WEIGHTS_LAYOUT_H__ */\n")

    print(f"[gen_weights_layout] Written: {args.out}")

if __name__ == "__main__":
    main()
