/*============================================================
 * gelu_worker.cpp — hardware GELU activation via a 16-entry int4 LUT
 * (W8A4: was a 256-entry int8 LUT before act_t shrank to ap_int<4>,
 * see fastvit_ip.h). gelu(x) ~= x * sigmoid(1.702*x).
 * gelu_rom[i+8] = round(gelu(i/7.0) * 7), i in [-8,7], clipped to
 * [-8,7] (the full ap_int<4> range -- note the surrounding pipeline's
 * OWN clamp convention is the narrower symmetric -7..7, see
 * fastvit_ip.h, but this table itself allows -8 defensively since it's
 * indexed by the full 4-bit code space, not just the -7..7 subset that
 * should ever actually appear).
 *
 * KNOWN GAP (see fastvit_ip.h header): this bakes in ONE assumed scale
 * (1/7) for every call site, but Phase 1's calibration produced a
 * DIFFERENT real-valued scale per layer -- this table cannot be
 * correct for all of them simultaneously. Matches a pre-existing
 * limitation in the original 256-entry/1-127-scale design (which also
 * assumed one uniform scale). Not fixed here -- accuracy work is
 * explicitly deferred per project decision (see project notes,
 * 2026-08-01 session). Values generated by:
 *   for i in range(-8,8): round(gelu(i/7.0)*7) -- see conversation
 *   history for the exact one-off Python snippet used.
 *============================================================*/

#include "gelu_worker.h"

static const act_t gelu_rom[16] = {
/* -8..-2 */  -1,  -1,  -1,  -1,  -1,  -1,  -1,
/*     -1 */   0,
/*  0..7  */   0,   1,   1,   2,   3,   4,   5,   6,
};

void gelu_worker(
    pack_t in_a[],
    pack_t out[],
    int    CH,
    int    H,
    int    W)
{
#pragma HLS INLINE off
#pragma HLS BIND_STORAGE variable=gelu_rom type=ROM_1P impl=LUTRAM

    /* W8A4: 8 nibble-packed act_t lanes per 32-bit pack_t word (was 4
     * byte lanes) -- see fastvit_ip.h. */
    int total   = CH * H * W;
    int n_words = (total + 7) >> 3;

    GELU_LOOP:
    for (int w = 0; w < n_words; w++) {
#pragma HLS PIPELINE II=1
        pack_t wa = in_a[w];
        pack_t wo;
        for (int b = 0; b < 8; b++) {
#pragma HLS UNROLL
            act_t a = (act_t)wa.range(b*4+3, b*4);
            ap_uint<4> idx = (ap_uint<4>)((int)a + 8);
            wo.range(b*4+3, b*4) = gelu_rom[idx];
        }
        out[w] = wo;
    }
}
